### ISSUE TITLE
multilabelBinaryRelevanceWrapper is not working properly for classif.glmnet

### ISSUE THREAD

**Issue by MariaErdmann** [mlr-org/mlr#958] opened 2016-06-20 07:48 UTC
I am not sure if this is a bug:
prediction for classif.glmnet wrapped to a multilabelBinaryRelevanceWrapper throws an error. 
In the example below I subset the yeast.task but using the whole task will cause the same error.

```
#load_all() 
yeast = getTaskData(yeast.task)
yeast = yeast[1:300,c(1:3, 113:117)]
labels = colnames(yeast)[1:3]
yeast.task = makeMultilabelTask(id = "multi", data = yeast, target = labels)
yeast.task

# Create multilavelBinaryRelevanceWrapper for classif.glmnet
lrn = makeLearner("classif.glmnet")
lrn2 = makeMultilabelBinaryRelevanceWrapper(lrn)
mod = train(lrn2, yeast.task)
pred = predict(mod, task2)
#Error in predict(mod, yeast.task) : 
#  Assertion on 'subset' failed: Must be of type 'integerish', not 'double'.

```

I tried to find out where it comes from but was not successful (yet).
All other binary (or multiclass) classification learners do work with the Wrapper though.

**Comment by catastrophic-failure** [comment] 2016-06-20 10:12
Happened to be on a ensemble in a real application. Perhaps it has something to do with the number of predictors, as I was trying attribute bagging.

```splus
lrn = makeLearner("regr.glmnet", alpha = 0.5)
lrn = makeBaggingWrapper(lrn, bw.iters = 500L, bw.replace = FALSE, bw.size = 1, bw.feats = 1/50)
res = benchmark(lrn, task, rdesc.outer, list(mse, expvar, timeboth))
#Warning in predict.WrappedModel(m, task, subset = train.i) :
#  Could not predict with learner regr.glmnet.bagged: Error in benchmark(lrn, IQ.tasks[[1]], #rdesc.outer, list(mse, expvar,  : 
#  Assertion on 'subset' failed: Must be of type 'integerish', not 'double'.
```


```

**Comment by schiffner** [comment] 2016-06-20 12:35
I only had time to look at this for a minute:

It turns out that the error occurs because `subset` has the value `0.01`.
My guess is that by partial matching `subset` gets confused with the parameter `s` of `glmnet` which is set to `0.01` in the mlr interface to `glmnet` (cp. `lrn$par.vals`).
So the core of the problem would be how to unambiguously pass the params in `par.vals` to `predict`.

**Comment by berndbischl** [comment] 2016-06-20 12:48
julia is correct. i figured out the same problem right now.
i hate r, this is soooo stupid.

here is the solution:
a) make the default of "subset" NULL everywhere and not missing
b) adapt the wrappers like this
    function(m) predict(m, newdata = .newdata, subset = NULL, ...)$data$prob.TRUE

(where subset is not explicitly used) 
this will ensure that we dont have partial matching
c) add the problem as a unit test
d) adapt docs

**Comment by berndbischl** [comment] 2016-06-29 01:50
@Coorsaa please do this.

**Comment by danielhomola** [comment] 2017-03-27 09:49
I ran into the same problem with `glmnet` and `makeBaggingWrapper`. Is this supposed to be fixed in the latest release? 

thanks
d

**Comment by berndbischl** [comment] 2017-03-29 12:57
@danielhomola 
yes this is supposed to be fixed. can you please post a reproducible example? otherwise we cannot help

**Comment by danielhomola** [comment] 2017-03-30 15:47
This is the shortest example I could come up with:

```{r}
library(mlr)
library(parallel)
library(parallelMap)
dataset = pid.task

lrn <- makeLearner("classif.glmnet", predict.type="response")
lrn = makeBaggingWrapper(lrn)
lrn = setPredictType(lrn, predict.type = "prob")

ctrl <- makeTuneControlRandom(maxit=10)
outer <- makeResampleDesc("CV", iters=3, stratify=T, predict = "both")

res <- resample(lrn, dataset, resampling=outer, models=T,
                show.info=F, measures=auc)  

```

But this is the example I want to be able to run:

```{r}
library(mlr)
library(parallel)
library(parallelMap)
dataset = pid.task

lrn <- makeLearner("classif.glmnet", predict.type="response")
lrn <- makeUndersampleWrapper(lrn)
lrn = makeBaggingWrapper(lrn)
lrn = setPredictType(lrn, predict.type = "prob")

ps <- makeParamSet(
  makeNumericParam("alpha", lower=0, upper=1),
  makeNumericParam("s", lower=0, upper=2, trafo=function(x) 10^x),
  makeNumericParam("usw.rate", lower=.5, upper=1)
)

ctrl <- makeTuneControlRandom(maxit=10)
outer <- makeResampleDesc("CV", iters=3, stratify=T, predict = "both")
inner <- makeResampleDesc("CV", iters=3, stratify=T)

lrn_wrap <- makeTuneWrapper(lrn, resampling=inner, par.set=ps, control=ctrl,
                            show.info=F, measures=auc)

parallelStartSocket(detectCores(), level="mlr.tuneParams")
res <- resample(lrn_wrap, dataset, resampling=outer, models=T,
                extract=getTuneResult, show.info=F, measures=auc)  
parallelStop()
```

**Comment by berndbischl** [comment] 2017-03-31 10:37
@danielhomola thank you for example. same problem as before.

the reason is, that the guys who fixed and reviewed this before, did not read what i suggested in the issue.
@Coorsaa @larskotthoff @giuseppec 

can you please reread the thread? i mean i said pretty clearly that we have to adapt ALL wrappers.
you then fixed this for JUST the multilabel binary relevance method. and 2 persons reviewed this, and said:
"all good"!

please adapt.

**Comment by berndbischl** [comment] 2017-03-31 10:38
please read what i said here, then compare with the diff that @Coorsaa provided, and you reviewed


> here is the solution:
> a) make the default of "subset" NULL everywhere and not missing
> b) adapt the wrappers like this
> function(m) predict(m, newdata = .newdata, subset = NULL, ...)$data$prob.TRUE
> 
> (where subset is not explicitly used)
> this will ensure that we dont have partial matching
> c) add the problem as a unit test
> d) adapt docs

**Closed** 2017-05-30 11:04 UTC
Labels: effort-simplefix, project - Learners, type-bug, type-question
