### ISSUE TITLE
Custom Learner not working with Parallel Map

### ISSUE THREAD

**Issue by nanokelvin** [mlr-org/mlr#1976] opened 2017-08-09 16:45 UTC
I've written a custom learner (edited ranger to calculate probabilities in the canonical fashion) and it works with resample, tuneParams, and benchmark generally, but fails when I try to use parallelMap, even when I follow the guidelines here: http://mlr-org.github.io/mlr-tutorial/release/html/parallelization/index.html

My code looks something like this:

```
parallelStartSocket(5,level='mlr.resample') 
parallelExport("trainLearner.classif.ranger_edit", "predictLearner.classif.ranger_edit")
res = tuneParams(rf_edit, task = task, resampling = rdesc,par.set = discrete_ps, control = ctrl, measures=list(lsr,brier,auc))
```

>  Error in UseMethod("trainLearner") : 
>   no applicable method for 'trainLearner' applied to an object of class "c('classif.ranger_edit', 'RLearnerClassif', 'RLearner', 'Learner')"

Which is different from the error mentioned on the tutorial page.  

So what else have I done wrong?

**Comment by larskotthoff** [comment] 2017-08-09 16:47
My guess is that you haven't installed the changed package and are using socket parallelization or something similar. This way, the old package without your new code will get loaded on the parallel slaves.

**Comment by berndbischl** [comment] 2017-08-09 16:49
no, the problem is that you didnt register the s3 methods. 

but you guys NEED to post fully reproducible examples, otherwise we cannot help

**Comment by berndbischl** [comment] 2017-08-09 16:50
wait no i am an idiot. it works with normal mlr, just fails in parallelmap

we still need a full example :)

**Comment by berndbischl** [comment] 2017-08-09 16:51
i guess it is a duplicate of this annoying thing here

https://github.com/mlr-org/mlr/issues/117

**Comment by berndbischl** [comment] 2017-08-09 16:52
that issue is bad, that it exists, and i hate it. 
but ir does contain a 1 line fix you could apply locally to make it run .....

is it that?

**Comment by nanokelvin** [comment] 2017-08-09 18:32
Yes, changing the parallel export line to this fixed this issue:

```
parallelExport("trainLearner.classif.ranger_edit", "predictLearner.classif.ranger_edit",level='mlr.resample')
```
Thanks for the help.

**Closed** 2017-08-09 18:36 UTC

**Comment by berndbischl** [comment] 2017-08-09 21:28
@larskotthoff 
would you be so kind to add this hint to the tutorial?

**Comment by larskotthoff** [comment] 2017-08-09 21:40
Done.
