### ISSUE TITLE
Partial dependence target scale not right

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#1232] opened 2016-09-09 22:14 UTC
When I run the examples from `generatePartialDependenceData` docs, the scale of the target doesn't look right. Any ideas?

Here is the first example in the documentation:

```
lrn = makeLearner("regr.svm")
fit = train(lrn, bh.task)
pd = generatePartialDependenceData(fit, bh.task, "lstat")
plotPartialDependence(pd, data = getTaskData(bh.task))
```
![image](https://cloud.githubusercontent.com/assets/4913951/18404532/0944e8de-76b9-11e6-8cb9-c269cdedbe1f.png)

The graph above doesn't look right. It appears the target variable is off by a few decimal places?

```
pd$data
         medv     lstat
1  0.05248820  1.730000
2  0.04980801  5.756667
3  0.04666540  9.783333
4  0.04337672 13.810000
5  0.04027198 17.836667
6  0.03764451 21.863333
7  0.03571056 25.890000
8  0.03458451 29.916667
9  0.03427200 33.943333
10 0.03468078 37.970000
```

**Comment by zmjones** [comment] 2016-09-10 01:25
the issue is with the weight function that i added recently. the default aggregation function is still the mean which means that the scale is off by a factor of 100. setting the aggregation function to sum will fix the issue in this case.

generally, i am not sure of the best way to solve this.

i could change the default aggregation function to sum and add a note in the documentation. however, if you wanted to use the variance this wouldn't work, since a weighted variance is 1 / n * sum(w * (x - mu)^2) and in the current implementation i use fun(x) * w / sum(w) which wouldn't work.

i am thinking maybe i should remove the weights function totally, and instead add the ability to pass additional arguments to the aggregation function, where the user can compute weights if they like. 

thoughts?

**Comment by larskotthoff** [comment] 2016-09-10 01:30
Hmm, it sounds like removing the weights and allowing the user to do this in the aggregation function is the best solution. It looks like at the moment it's easy to get misleading results if the two don't match and impossible to check if they do in the function.

**Comment by zmjones** [comment] 2016-09-10 01:38
yea ok. will do that now.

**Comment by zmjones** [comment] 2016-09-10 02:05
so the problem with this is that to compute weights you need the training data and you need the prediction grid which is generated internally. in the function were the weights would be computed this object is called newdata. i'd like to be able to pass newdata (along with the training data) into the aggregation function so that users can compute weights but i would like the default aggregation function to still be mean and to not bother users with this if they aren't computing weights.

i guess this comes down to an environments issue. is there a way to do this without side effects? that is, make data and newdata available to a function the user passes in but without adding these things as arguments? adding them as arguments won't work generally because if the fun argument is just mean, for example, you'll get an unused argument error.

**Comment by larskotthoff** [comment] 2016-09-10 02:23
I don't think that messing with the environment is the right thing. What if you just documented the function prototype prominently with an example how to use mean (wrapped in a function that takes and discards the additional arguments)?

**Comment by zmjones** [comment] 2016-09-10 02:38
hmmm yea i guess. i don't love this solution though since it makes the aggregation function step much more complicated for a seemingly trivial reason. i am going to do some more research to see if there is a way around this. if i can't find anything then i'll add this tomorrow.

**Comment by zmjones** [comment] 2016-09-10 02:45
ah i think i have a workaround. 

i could create a new function which calls the user `fun` arg, looks at its arguments to see if they contain `newdata` and `data`, and if so pass them in. this would be documented of course.

what do you think?

**Comment by larskotthoff** [comment] 2016-09-10 03:03
Sounds good.

**Comment by berndbischl** [comment] 2016-09-10 19:59
@zmjones 
hi, what is the status here? i would like to really release soon. 
but looking at what mason posted above this seems like a really bad bug and affects the most trivial example. i dont want to push buggy code on CRAN

(and we NEED better tests for this... this happens now the umpteenth time .... )

**Comment by zmjones** [comment] 2016-09-11 13:54
It will be done today, was just busy yesterday.

Yea sure it would be nice for the tests to have caught this. I guess I can modify existing tests so that they would have caught this. All the spate of recent bugs is due to this weighting stuff I was working. No problems in the core code.

**Comment by zmjones** [comment] 2016-09-12 23:11
fixed by https://github.com/mlr-org/mlr/pull/1235

**Closed by zmjones** 2016-09-12 23:11 UTC
Labels: bug, prio-severe

**Comment by berndbischl** [comment] 2016-09-13 16:00
thx, zach
