### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by AlexYoung757** [mlr-org/mlr#2290] opened 2018-06-11 16:58 UTC
when i use  generateFilterValuesData() method to feature select ，some errors as follow：

Error in .jcall("weka/filters/Filter", "Lweka/core/Instances;", "useFilter",  : 
  java.lang.IllegalArgumentException: A duplicate bin range was detected. Try increasing the bin range precision

here is my code：
```r
xgb.task <- makeClassifTask(data = tr2, target = 'TARGET')
xgb.task.over <- oversample(xgb.task, rate = 17)
fv_time <- system.time(
  fv <- generateFilterValuesData(
    xgb.task.over,
    method = c('information.gain')
  )
)
```
the  dataframe “tr2 ” contains 205 variables ，and everyone is numerical.

here is my  sessionInfo():
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] parallelMap_1.3   mlr_2.12.1        ParamHelpers_1.10 data.table_1.11.4
 [5] magrittr_1.5      forcats_0.3.0     stringr_1.3.1     dplyr_0.7.5      
 [9] purrr_0.2.5       readr_1.1.1       tidyr_0.8.1       tibble_1.4.2     
[13] ggplot2_2.2.1     tidyverse_1.2.1  

loaded via a namespace (and not attached):
 [1] RWeka_0.4-37        tidyselect_0.2.4    reshape2_1.4.3      rJava_0.9-9        
 [5] splines_3.5.0       haven_1.1.1         lattice_0.20-35     colorspace_1.3-2   
 [9] yaml_2.1.18         FSelector_0.31      survival_2.42-3     rlang_0.2.0        
[13] pillar_1.2.2        foreign_0.8-70      glue_1.2.0          entropy_1.2.1      
[17] modelr_0.1.1        readxl_1.1.0        bindrcpp_0.2.2      bindr_0.1.1        
[21] plyr_1.8.4          munsell_0.4.3       gtable_0.2.0        cellranger_1.1.0   
[25] rvest_0.3.2         psych_1.8.4         RWekajars_3.9.2-1   parallel_3.5.0     
[29] broom_0.4.4         Rcpp_0.12.17        scales_0.5.0        backports_1.1.2    
[33] checkmate_1.8.5     jsonlite_1.5        mnormt_1.5-5        digest_0.6.15      
[37] hms_0.4.2           stringi_1.2.2       BBmisc_1.11         grid_3.5.0         
[41] cli_1.0.0           tools_3.5.0         lazyeval_0.2.1      randomForest_4.6-14
[45] crayon_1.3.4        pkgconfig_2.0.1     Matrix_1.2-14       xml2_1.2.0         
[49] lubridate_1.7.4     assertthat_0.2.0    httr_1.3.1          rstudioapi_0.7     
[53] R6_2.2.2            nlme_3.1-137        compiler_3.5.0     

how should i do, can anyone help me?

**Comment by mllg** [comment] 2018-06-12 15:48
Cannot reproduce without the data. Works fine with `sonar.task`. Can you provide a more complete Reprex?

**Comment by AlexYoung757** [comment] 2018-06-13 01:55
need original data or anything else?

**Comment by larskotthoff** [comment] 2018-06-17 18:41
The original data that allows to reproduce the problem.

**Comment by BharatAD** [comment] 2018-08-08 09:42
[sample.zip](https://github.com/mlr-org/mlr/files/2269752/sample.zip)

Hi i would like to reopen this issue. The data is attached and i simply used the code:
`corrs<-cfs(formula=label~.,data=dataset)
`

**Comment by jakob-r** [comment] 2018-08-15 09:07
Please include a complete reproducible example. It also has to read the data of the zip file you provided.

**Comment by mb706** [comment] 2018-10-21 17:36
Many FSelector filters try to discretize data using `RWeka::Discretize`. This fails if value differences are too small, because, and this is admittedly a bit dumb, the names of the discrete categories use fixed point representation and start to collide:
```r
> bigdata <- data.frame(a = letters[1:4], b = 1:4)
> smalldata <- data.frame(a = letters[1:4], b = 1:4 / 1e6)
> vsmalldata <- data.frame(a = letters[1:4], b = 1:4 / 1e7)
> RWeka::Discretize(a ~ b, data = bigdata)
             b a
1 '(-inf-1.5]' a
2  '(1.5-2.5]' b
3  '(2.5-3.5]' c
4  '(3.5-inf)' d
> RWeka::Discretize(a ~ b, data = smalldata)
                      b a
1     '(-inf-0.000002]' a
2 '(0.000002-0.000002]' b
3 '(0.000002-0.000003]' c
4      '(0.000003-inf)' d
> RWeka::Discretize(a ~ b, data = vsmalldata)
Error in .jcall("weka/filters/Filter", "Lweka/core/Instances;", "useFilter",  :
  java.lang.IllegalArgumentException: A duplicate bin range was detected. Try increasing the bin range precision.
```
This propagates to feature filters:
```r
> smalltask <- makeClassifTask("df", smalldata, "a")
> vsmalltask <- makeClassifTask("df", vsmalldata, "a")
> filterFeatures(vsmalltask, "information.gain", abs = 1)  # error!
Error in .jcall("weka/filters/Filter", "Lweka/core/Instances;", "useFilter",  :
  java.lang.IllegalArgumentException: A duplicate bin range was detected. Try increasing the bin range precision.
> filterFeatures(smalltask, "information.gain", abs = 1)  # no discretization error -> works
Supervised task: df
Type: classif
[...]
```

A solution is to multiply features by a preferably large factor. This can for example be done using [mlrCPO](/mlr-org/mlrCPO):
```r
scaler <- cpoApplyFun(function(x) x * 1000, affect.type = "numeric")
# example application:
filterFeatures(smalltask %>>% scaler, "information.gain", abs = 1)
```

**Comment by pat-s** [comment] 2018-11-07 22:19
@mb706 	thanks for the heads-up! I assume that the workaround solves the issue for now. Also OP did not respond for quite some time. Closing.

**Closed by pat-s** 2018-11-07 22:19 UTC
