### ISSUE TITLE
Failures with dev testthat

### ISSUE THREAD

**Issue by hadley** [mlr-org/mlr#535] opened 2015-10-13 20:41 UTC
I see

```
checking tests ... ERROR
Running the tests in ‘tests/run-base.R’ failed.
Last 13 lines of output:
  19: pre_process_options(method, column_types)
  
  testthat results ================================================================
  OK: 1098 SKIPPED: 0 FAILED: 1
  1. Error: basic PreprocWrapperCaret works 
  
  Error: testthat unit tests failed
  In addition: Warning messages:
  1: In lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  :
    one multinomial or binomial class has fewer than 8  observations; dangerous ground
  2: Non Lab interpolation is deprecated 
  3: Non Lab interpolation is deprecated 
  Execution halted
```
```
DONE
Status: 1 ERROR
```

I'm planning to submit to CRAN this afternoon, so you may need to prepare a new release soon. Not sure why this didn't pop up in my last round of revdep tests

**Comment by larskotthoff** [comment] 2015-10-13 20:42
Thanks Hadley. This was caused by a new release of caret yesterday and has been fixed in 3729f37f977770b0618c9f42e63ca49c62634efe.

**Closed by larskotthoff** 2015-10-13 20:42 UTC
