### ISSUE TITLE
Examples/tests fail when suggested packages are not available

### ISSUE THREAD

**Issue by hadley** [mlr-org/mlr#292] opened 2015-05-05 15:29 UTC
```
checking examples ... ERROR
Running examples in ‘mlr-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: plotFilterValues
> ### Title: Plot filter values.
> ### Aliases: plotFilterValues
> 
> ### ** Examples
> 
> fv = getFilterValues(iris.task, method = "chi.squared")
Error in requirePackages(filter$pkg, why = "getFilterValues", default.method = "load") : 
  For getFilterValues please install the following packages: FSelector
Calls: getFilterValues -> requirePackages -> stopf
Execution halted
```
```
checking tests ... ERROR
Running the tests in ‘tests/run-base.R’ failed.
Last 13 lines of output:
  9. Failure (@test_base_checkTaskLearner.R#11): checkTaskLearner 
  1. Error: clustering performance 
  2. Error: clustering resample 
  3. Error: clustering benchmark 
  4. Error: clustering tune 
  5. Error: plotLearnerPrediction 
  6. Error: predict preserves rownames 
  7. Error: predict.threshold 
  8. Error: tune 
  9. ...
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by berndbischl** [comment] 2015-05-05 15:42
This is conceptually a duplicate of berndbischl/ParamHelpers#35

And I started the discussion in the other thread.

**Comment by berndbischl** [comment] 2015-07-15 20:14
Cannot fix now.

**Closed by berndbischl** 2015-07-15 20:14 UTC
