### ISSUE TITLE
xgboost doesn't work with makeDownsampleWrapper

### ISSUE THREAD

**Issue by rpinsler** [mlr-org/mlr#492] opened 2015-09-23 14:08 UTC
Hi all,

if you call `makeDownsampleWrapper("classif.xgboost")` you receive an error

```
Error in (function (..., params, forbidden = NULL)  : 
  You can only use one of ... or params!
```

which is a call to `makeParamSet`. I guess the problem is that xgboost has a parameter called `params`, which leads to a conflict with the `params` argument of the function. This might be a problem for other learners as well.

**Comment by rpinsler** [comment] 2015-09-23 17:35
As expected, it works once I replace the `params` parameter with `parms` (as it is called e.g. in *classif.rpart*). The argument currently isn't used anyway. *classif.xgboost* and *regr.xgboost* also seem to be the only learners with this problem:
```
checkParamName <- function(pname) {
  packages <- lapply(listLearners(), function(learner) {
    if (pname %in% names(getParamSet(learner)$pars)) return(learner)
  })
  packages[!vapply(packages, is.null, logical(1))]
} 
checkParamNames("params")
```

outputs:
```
[[1]]
[1] "classif.xgboost"

[[2]]
[1] "regr.xgboost"
```

Maybe this should be a unit test?

**Comment by berndbischl** [comment] 2015-09-23 18:42
thx for the nice report. we can ourselves merge AND UNIT TEST this quickly.

but just for the fun of it, and as you seem to be more active with mlr, would you be up to generate a pull request? we have explained how to do this in wiki.

**Comment by rpinsler** [comment] 2015-09-23 19:07
Sure, I can try tomorrow. About the unit test: should this test for all learners at once or just one? Where do I put it?

**Comment by berndbischl** [comment] 2015-09-23 20:37
Regarding the issue itself: 
These name clashes are very hard to avoid, in general, when we join the param sets.
In order to make it easier, we give the wrapper params very specific names.

**Comment by berndbischl** [comment] 2015-09-23 20:38
But: I cannot reproduce. This runs for me
lrn = makeDownsampleWrapper("classif.xgboost")

I am using GH versions of mlr and ParamHelpers

**Comment by berndbischl** [comment] 2015-09-23 20:42
in the current mlr version, xgboost does not have this (unused) param anymore. what i said above is actually untrue, as the name clash happens in makeParamSet, as you reported, not the wrapper.

**Comment by berndbischl** [comment] 2015-09-23 20:44
i can try to fix this in PH but cannot promise. but this bug is here solved right?

**Comment by rpinsler** [comment] 2015-09-23 21:18
The above assignment also works for me, but I get the same error when I print it (I didn't assign it to a variable before, so it got printed automatically):

```
[...] # error occurs
10: do.call(makeParamSet, pars)
9: c.ParamSet(learner$par.set, getParamSet(learner$next.learner))
8: c(learner$par.set, getParamSet(learner$next.learner))
7: getParamSet.BaseWrapper(learner)
6: getParamSet(learner)
5: getHyperParsString(x)
4: cat("Learner ", x$id, " from package ", collapse(cleanupPackageNames(x$package)), 
       "\n", "Type: ", x$type, "\n", "Name: ", x$name, "; Short name: ", 
       x$short.name, "\n", "Class: ", class(x)[1L], "\n", "Properties: ", 
       collapse(getLearnerProperties(x)), "\n", "Predict-Type: ", 
       x$predict.type, "\n", "Hyperparameters: ", getHyperParsString(x), 
       "\n\n", sep = "")
3: print.Learner(x)
2: print.BaseWrapper(lrn)
1: print(lrn)
```

That said, I agree that makeDownsampleWrapper itself is not the problem. Didn't realize makeParamSet isn't an mlr function, so yeah, if you prefer changing the signature of makeParamSet, it's not an mlr issue and therefore "solved here".

Dunno what you mean by "in the current mlr version, xgboost does not have this (unused) param anymore". If I check [the code](https://github.com/mlr-org/mlr/blob/master/R/RLearner_classif_xgboost.R),  it still has.

**Comment by berndbischl** [comment] 2015-09-23 22:20
> Dunno what you mean by "in the current mlr version, xgboost does not have this (unused) param 
> anymore". If I check the code, it still has.

Sorry, I looked into the wrong file. 

But you cannot do much here. I will try to take this over.
But 'params' we really dont read when  we call xgb.train right? Because pass all stuff directly?
So its removal now does make sense?

@giuseppec

**Comment by giuseppec** [comment] 2015-09-24 09:19
I think we can remove the `params` parameter, if we are okay with forcing the user to pass the parameters directly. And we maybe should unit test if xgboost does different things when a parameter is passed in the `...` instead of in the list of `params`.

**Comment by berndbischl** [comment] 2015-09-24 09:22
> if we are okay with forcing the user to pass the parameters directly

that only makes it easier for the user. he gets type checks and can tune. what it in "params" cannot easily be tuned.

**Comment by berndbischl** [comment] 2015-09-24 09:28
regarding the test for xgboost: i find this a bit overboard for now

**Comment by rpinsler** [comment] 2015-09-24 09:34
Agreed. Can you let me know when it's fixed in PH?

**Comment by berndbischl** [comment] 2015-09-24 09:36
Doing it now. We will also remove "param" in xgboost. so that would imply a "double fix".

**Comment by berndbischl** [comment] 2015-09-24 09:37
Should be fixed in PH now.

**Closed** 2015-09-24 11:03 UTC
Labels: bug

**Comment by berndbischl** [comment] 2015-09-24 12:53
see also my comments in the PR. I removed 'param' from xgboost learners
