### ISSUE TITLE
learner 'classif.classiFunc.kernel' does not support that!" when tuning some specific Classification Model

### ISSUE THREAD

**Issue by FlyImagi** [mlr-org/mlr#2780] opened 2020-08-07 04:05 UTC
I recently trying to model  ('classif.classiFunc.kernel', 'classif.classiFunc.knn', 'classif.fdausc.glm'), for my understanding, these requires functional data correct? does this dataframe enough to count as functional data?

```
str(df)
'data.frame':	208 obs. of  5 variables:
 $ tpsa      : num  12 49.3 50.5 37.4 37.4 ...
 $ nbasic    : Factor w/ 2 levels "0","1": 2 1 2 1 2 2 2 2 2 2 ...
 $ vsa_hyd   : num  167.1 92.6 295.2 319.1 299.7 ...
 $ vsa_acc   : num  0 13.57 8.19 8.19 8.19 ...
 $ andrewbind: num  3.4 -3.3 12.8 12.8 10.3 10 10.4 15.9 12.9 9.5 ...
```

```
Error in checkLearnerBeforeTrain(task, learner, weights) : 
  Task 'df' has numeric inputs in 'tpsa, vsa_hyd, vsa_acc, andrewbind', but learner 'classif.classiFunc.kernel' does not support that! 

 Error in checkLearnerBeforeTrain(task, learner, weights) : 
  Task 'df' has numeric inputs in 'tpsa, vsa_hyd, vsa_acc, andrewbind', but learner 'classif.classiFunc.knn' does not support that! 

 Error in checkLearnerBeforeTrain(task, learner, weights) : 
  Task 'df' has numeric inputs in 'tpsa, vsa_hyd, vsa_acc, andrewbind', but learner 'classif.fdausc.glm' does not support that! 
```

Note: I use nbasic as response variable as the others is predictor

What Should I do to make correction for this behaviour?

**Comment by pat-s** [comment] 2020-08-07 05:17
Hi,

thanks for posting your issue here.
Please provide a [reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example), preferably using the [reprex](https://github.com/tidyverse/reprex) package.

**Comment by FlyImagi** [comment] 2020-08-07 06:27
My R code is enveloped in function, so let I define manually what similiar to my issues.. Here is some Reproducible Example:

```
library(caret)
data("BloodBrain")
dummy_data_continous <- bbbDescr[,which(colnames(bbbDescr) %in% 
                                            c("tpsa","vsa_hyd","vsa_acc","andrewbind"))]
dummy_data_classif_continous <-  bbbDescr[,which(colnames(bbbDescr) %in% 
                                                     c("nbasic","tpsa","vsa_hyd","vsa_acc","andrewbind"))]
dummy_data_classif_continous$nbasic <- as.factor(dummy_data_classif_continous$nbasic)

     param_eval
[1] "hyperparam <- makeParamSet(
makeNumericParam(\"h\",lower = 0,upper=1000), makeDiscreteParam(\"metric\",values = c(\"cosine1\", \"cosine2\", \"eJaccard1\", \"eJaccard2\", \"eDice1\", \"eDice2\", \"eDice3\", \"correlation\", \"Euclidean1\", \"Euclidean2\", \"Mahalanobis\", \"Bhjattacharyya\", \"Manhattan1\", \"Manhattan2\", \"Manhattan3\", \"Manhattan4\", \"supremum1\", \"supremum2\", \"supremum3\", \"supremum4\", \"supremum5\", \"Minkowski1\", \"Minkowski2\", \"Canberra\", \"Wave1\", \"Wave2\", \"divergence\", \"Kullback1\", \"Kullback2\", \"Bray1\", \"Bray2\", \"Soergel\", \"Podani1\", \"Podani2\", \"Chord\", \"Geodesic\", \"Whittaker\", \"Hellinger\", \"fJaccard1\", \"fJaccard2\", \"shortEuclidean\", \"mean\", \"relAreas\", \"jump\", \"globMax\", \"globMin\", \"points\", \"custom.metric\", \"amplitudeDistance\", \"phaseDistance\", \"FisherRao\", \"elasticMetric\", \"elasticDistance\", \"dtwPath\", \"rucrdtw\", \"rucred\")), makeDiscreteParam(\"ker\",values = c(\"Ker.norm\", \"Ker.cos\", \"Ker.epa\", \"Ker.tri\", \"Ker.quar\", \"Ker.unif\", \"AKer.norm\", \"AKer.cos\", \"AKer.epa\", \"AKer.tri\", \"AKer.quar\", \"AKer.unif\", \"custom.ker\")), makeIntegerParam(\"nderiv\",lower = 0,upper=0), makeDiscreteParam(\"deriv.method\",values = c(\"base.diff\", \"fda.deriv.fd\")), makeNumericParam(\"dmin\",lower = 0,upper=1), makeNumericParam(\"dmax\",lower = 0,upper=1), makeNumericParam(\"dmin1\",lower = 0,upper=1), makeNumericParam(\"dmax1\",lower = 0,upper=1), makeNumericParam(\"dmin2\",lower = 0,upper=1), makeNumericParam(\"dmax2\",lower = 0,upper=1), makeNumericParam(\"t1\",lower = 0,upper=1), makeNumericParam(\"t2\",lower = 0,upper=1), makeNumericParam(\"p\",lower = -2000,upper=2000), makeNumericParam(\"lambda\",lower = 0,upper=1000), makeDiscreteParam(\"method\",values = c(\"chol\", \"qr\")), makeNumericParam(\"dfscale\",lower = 0,upper=1000))"

      task <- makeClassifTask(data = dummy_data_classif_continous, 
                              target = "nbasic")
      lrn <- makeLearner(cl = 'classif.classiFunc.kernel', fix.factors.prediction = TRUE)

    hyper_search <- makeTuneControlRandom(maxit = 20)
    resampling_method <- makeResampleDesc("cv")
    eval(parse(text=param_eval))

    # Perform tuning
    lrn_tune <- tuneParams(learner = lrn, task = task, 
                           resampling = resampling_method, 
                           control = hyper_search, par.set = hyperparam, 
                           measures=list(acc,mmce))

```

**Comment by pat-s** [comment] 2020-08-08 14:01
A few things first:
- Don't make issue title so long.  Put error messages into the body.
- Try to format your code in a way that it does not exceed the width of the comment window. See the {styler} package for help regarding code formatting.
- You should not need `\` backticks to escape quotes, even if you are on Windows.

Please reformat your code again to that it can be run and presents a standalone example. Your last revision does not.

**Comment by FlyImagi** [comment] 2020-08-09 14:18
Like this?

```
library(caret)
data("BloodBrain")
dummy_data_continous <- bbbDescr[,which(colnames(bbbDescr) %in% 
                                            c("tpsa","vsa_hyd","vsa_acc","andrewbind"))]
dummy_data_classif_continous <-  bbbDescr[,which(colnames(bbbDescr) %in% 
                                                     c("nbasic","tpsa","vsa_hyd","vsa_acc","andrewbind"))]
dummy_data_classif_continous$nbasic <- as.factor(dummy_data_classif_continous$nbasic)

hyperparam <- makeParamSet(
  makeNumericParam("h",lower = 0,upper=1000), 
  makeDiscreteParam("metric",values = c("cosine1", "cosine2", "eJaccard1", 
  "eJaccard2", "eDice1", "eDice2", "eDice3", "correlation", "Euclidean1", 
  "Euclidean2", "Mahalanobis", "Bhjattacharyya", "Manhattan1", "Manhattan2", 
  "Manhattan3", "Manhattan4", "supremum1", "supremum2", "supremum3", 
  "supremum4", "supremum5", "Minkowski1", "Minkowski2", "Canberra", 
  "Wave1", "Wave2", "divergence", "Kullback1", "Kullback2", "Bray1", 
  "Bray2", "Soergel", "Podani1", "Podani2", "Chord", "Geodesic", 
  "Whittaker", "Hellinger", "fJaccard1", "fJaccard2", "shortEuclidean", 
  "mean", "relAreas", "jump", "globMax", "globMin", "points", 
  "custom.metric", "amplitudeDistance", "phaseDistance", "FisherRao", 
  "elasticMetric", "elasticDistance", "dtwPath", "rucrdtw", "rucred")), 
  makeDiscreteParam("ker",values = c("Ker.norm", "Ker.cos", "Ker.epa", 
  "Ker.tri", "Ker.quar", "Ker.unif", "AKer.norm", "AKer.cos", "AKer.epa", 
  "AKer.tri", "AKer.quar", "AKer.unif", "custom.ker")), 
  makeIntegerParam("nderiv",lower = 0,upper=0), 
  makeDiscreteParam("deriv.method",values = c("base.diff", "fda.deriv.fd")), 
  makeNumericParam("dmin",lower = 0,upper=1), 
  makeNumericParam("dmax",lower = 0,upper=1), 
  makeNumericParam("dmin1",lower = 0,upper=1), 
  makeNumericParam("dmax1",lower = 0,upper=1), 
  makeNumericParam("dmin2",lower = 0,upper=1), 
  makeNumericParam("dmax2",lower = 0,upper=1), 
  makeNumericParam("t1",lower = 0,upper=1), 
  makeNumericParam("t2",lower = 0,upper=1), 
  makeNumericParam("p",lower = -2000,upper=2000), 
  makeNumericParam("lambda",lower = 0,upper=1000), 
  makeDiscreteParam("method",values = c("chol", "qr")), 
  makeNumericParam("dfscale",lower = 0,upper=1000)
)

task <- makeClassifTask(data = dummy_data_classif_continous, 
                              target = "nbasic")
lrn <- makeLearner(cl = 'classif.classiFunc.kernel', fix.factors.prediction = TRUE)

hyper_search <- makeTuneControlRandom(maxit = 20)
resampling_method <- makeResampleDesc("cv")
eval(parse(text=param_eval))

# Perform tuning
lrn_tune <- tuneParams(learner = lrn, task = task, 
                           resampling = resampling_method, 
                           control = hyper_search, par.set = hyperparam, 
                           measures=list(acc,mmce))
```

**Comment by pat-s** [comment] 2020-08-10 05:27
We are getting there but the example still does not run. Have you tried it? When starting a new session, the code should run until the error you want to discuss comes up.
Again, the {reprex} package helps.


Also note that by appending `r` behind the three backticks which initiate the code blocks you can get code highlighting for R on GitHub.

The title is better now.

**Comment by FlyImagi** [comment] 2020-08-10 08:39
@pat-s edited code above, I forget adding mlr packages in beginning

**Comment by pat-s** [comment] 2020-08-11 07:09
There is no learner called `classif.classiFunc.kernel` in the latest {mlr} version.

Are you using an older version of {mlr}? Again, a reprex would be great. This also includes a sessionInfo().
Learning to post good issues costs some time but is really worth it.

On the other side, note that I probably won't be able to help you with with is required for functional data as this is not my field of expertise.

Also note that we recommend to use {mlr3} for new studies.

**Comment by FlyImagi** [comment] 2020-08-12 03:27
Yes i am using an older version of MLR, since I am also still not familiar with MLR3 right now

**Comment by pat-s** [comment] 2020-08-12 16:19
I don't have resources to look up what functional learners require. However, this should not be too hard to find out? You can check the underlying packages or maybe there is even some info in the [mlr tutorial page about functional data](https://mlr.mlr-org.com/articles/tutorial/functional_data.html)?

You can compare your data with the example data that is used there.

**Comment by FlyImagi** [comment] 2020-08-13 03:47
I see, thank you for the given resources, I will look into it

**Comment by FlyImagi** [comment] 2020-08-13 10:35
I am following the tutorial, but I Think the example itself doesn't run smoothly, here is some reproducible example:

```
# Load required packages
library(FDboost)
library(ggplot2)

# Plot NIR curve for first observarion
data(fuelSubset, package = "FDboost")
str(fuelSubset)

df = data.frame(fuelSubset[c("heatan", "h2o", "UVVIS", "NIR")])
str(df[, 1:5])

library(mlr)
# fd.features is a named list, where each name corresponds to the name of the 
# functional feature and the values to the respective column indices or column names.
fd.features = list("UVVIS" = 3:136, "NIR" = 137:367)
fdf = makeFunctionalData(df, fd.features = fd.features)

tsk1 = makeRegrTask("fuelsubset", data = fdf, target = "heatan")
tsk1

# Create an FDboost learner for regression
fdalrn = makeLearner("regr.FDboost")

m = train(learner = fdalrn, task = tsk1)
```

the Error popups is as follows:
`Error in colnames(x) : argument "x" is missing, with no default`

**Comment by pat-s** [comment] 2020-08-13 11:53
The example is using the latest version of {mlr} and is checked every day to ensure that everything is working. I cannot speak for older versions and we won't check against them.

Update your packages and R version and most likely everything will be fine.

Note though that {FDboost} was just recently removed from CRAN (again) and we are likely removing the learner in the near future. So this example won't run anyways currently.

**Comment by FlyImagi** [comment] 2020-08-14 04:05
I see, directly running reprex using mlr3 is fine, but there is some warning:

```
UVVIS is not centered per column, inducing a non-centered effect.
NIR is not centered per column, inducing a non-centered effect.
```

I want to ask a few things:
1) is mlr3 listlearners doesn't the same as mlr? since you stated that `classif.classiFunc.kernel` dont exist at mlr last version, but I can get the param set fine using `getParamSet("classif.classiFunc.kernel")` in the olde version
2) will mlr3 updated to some extent in the future and released mlr4? since learning each version can take some time,

Thank you for your guide @pat-s

**Comment by pat-s** [comment] 2020-08-14 05:24
> if it so, how can I get exact listLearners available for mlr3?

```
library(mlr3)
mlr_learners()
```

> is mlr3 listlearners doesn't the same as mlr?

Most things are substantially different and you are encouraged to read the [mlr3book](https://mlr3book.mlr-org.com/) carefully.
However, it looks like we do not yet have FDA support in {mlr3} yet: https://github.com/mlr-org/mlr3fda.

Do not use {Paramhelpers} with {mlr3} but instead use {paradox}. 

Maybe @pfistfl Has an idea how to proceed here?

I am going to close this issue here because we are drifting off-topic and the issue is becoming quite long.
Thanks for using mlr/mlr3 - please ask separate issues/usage questions in new topics, preferred via Stackoverflow as more users will see the questions there. Thanks!

**Closed by pat-s** 2020-08-14 05:24 UTC
Labels: type-question
