### ISSUE TITLE
Why does generateFeatureImportanceData() take a learner/task rather than a trained model?

### ISSUE THREAD

**Issue by Prometheus77** [mlr-org/mlr#2722] opened 2020-01-23 16:47 UTC
## Description

Permutation importance is usually applied to already trained models, as it was originally described in Leo Breiman's classic "Random Forests" paper from 2001. In mlr, the generateFeatureImportanceData() requires a learner and task, and can't take a pre-trained model, which is not only more expensive from a compute perspective, it is less useful if your goal is to describe the importance of a feature in a specific model, as opposed to the generic usefulness of a feature in predicting a target variable in a dataset.

Can we consider either changing the function, or adding this as an option?

**Comment by jakob-r** [comment] 2020-01-23 16:55
You are certainly right. This was a bad design choice. But the mlr team is now completely dedicated to mlr3 and we will only fix bugs in mlr. However, you are welcome to do a PR.

**Comment by pat-s** [comment] 2020-01-23 18:55
We won't change the function for backward comp.
Also we will not put work into this as it is not a bug but just a bad design choice.

Happy to review a PR if you want to put in work to add that option.

**Comment by Prometheus77** [comment] 2020-01-24 02:34
Sure, I'll take a crack at it.

**Comment by Prometheus77** [comment] 2020-01-24 07:19
I've got a working branch. Dumb question ... how do I submit a PR if I don't have permission to push to a branch?

**Comment by pat-s** [comment] 2020-01-24 07:24
Via your fork.

**Comment by albersonmiranda** [comment] 2020-02-06 19:38
`getFeatureImportance()` works on trained models and might be what you're looking for.

**Comment by pat-s** [comment] 2020-02-07 07:17
> getFeatureImportance() works on trained models and might be what you're looking for.

Only extracts models built-in feat imp measures, does not apply to external permutation importance.

@Prometheus77 Do you still want open a PR?

**Comment by Prometheus77** [comment] 2020-02-07 15:59
Yep, will do today. Got distracted with work stuff.

**Comment by pat-s** [comment] 2020-02-17 15:19
Closing for now, feel free to open a PR when you have time :)

**Closed by pat-s** 2020-02-17 15:19 UTC
Labels: type-enhancement
