### ISSUE TITLE
mlr 2.7: Error in FUN(X[[i]], ...) : Column name contains special characters: ...

### ISSUE THREAD

**Issue by sanmai-NL** [mlr-org/mlr#637] opened 2015-12-21 12:59 UTC
In my design matrix data frame, text tokens are variables and I would like to keep the column names. Why does `mlr`  refuse these column names? In this case, the column name is 'af .'.

```
 8: makeSupervisedTask("classif", data, target, weights, blocking, fixup.data =
 9: SupervisedTask.R#1: makeTask(type = type, data = data, weights = weights, b
10: checkColumnNames(data, "data")
11: lapply(cns, function(cn) {
    if (!deparse(as.name(cn), backtick = TRUE) ==
12: FUN(X[[i]], ...)
13: stopf("Column name contains special characters: %s", cn)
```
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          2.1                         
year           2015                        
month          06                          
day            18                          
svn rev        68531                       
language       R                           
version.string R version 3.2.1 (2015-06-18)
nickname       World-Famous Astronaut  
```

**Comment by berndbischl** [comment] 2015-12-21 13:15
Well:
The problem is that I dont NOT know of any standard in R, what is allowed in column names and what is not. And R also does not really enforce or check this.

What I DO know is that some operations in R and also especially training methods will fail, if weirdly named columns are used. Because we wanted to protect users against these problems, we introduced this check. 

I do know that it is maybe too conservative. I am happy to discuss this, but we need a carefully selected standard where we can ensure nothing bad happens

**Comment by berndbischl** [comment] 2015-12-21 13:21
Well, a standards in R might be what make.names thinks of that string. And in your case that does not pass through unchanged.

**Comment by sanmai-NL** [comment] 2015-12-21 14:11
`make.names` is indeed the rule, but only for identifiers in R source code. Names are just elements of attribute, basically a character vector, and character vectors can contain any `C` strings. Modifying the column names is of course also a useful compromise, though I personally would probably get collisions with that. I'd rather drop the names entirely then, and keep them somewhere separately. I suppose this will make variable importance interpretation a bit harder though. In conclusion, unless the cases where unusual column names are well-known/articulated, it is a bit disenchanting to experience such a check refuse your data whereas it was thus far handled without problem in R and Rcpp.

I saw you discuss your validity/dynamic type/class checks in some other tickets as well. I think a good solution to a number of issues you now have would be to use [S4 object oriented programming](http://adv-r.had.co.nz/S4.html). This standard mechanism will check the classes of arguments automatically, transparently and without much overhead or any troublesome dependencies, and will indirectly also structure your source code base and documentation. In addition you can add further (standardized!) validity checks. Then you can add tests for all learners, insofar you do not have them yet, and solve any issues with column names upstream. If the issue is not solved satisfactorily upstream, you can implement that as a validity check and warn the user.[Bioconductor folks have [a lot of experience with S4 and use it effectively](http://master.bioconductor.org/help/course-materials/2010/AdvancedR/S4InBioconductor.pdf).

**Comment by berndbischl** [comment] 2015-12-21 16:13
1) Well, I am open to suggestions, but they need to be concrete and good. I could introduce an option to disable this check. Or before, we can run a few extra tests, where strange names actually cause a problem. Do you have something better?

2) Regarding S4:
Believe me, I have a lot of experience with S4 as well. I still have probably more years of Java experience then R (maybe they are equal now).
So when I came to R, guess which "dialect" I chose. S4. mlr actually existed some *years* in a prelim version in S4. I learned the hard way how much S4 sucks. It gives you basically nothing of the niceties of "true OO" (well, whatever that actually is precisely), but bloats your code a lot. I could also produce very weird bugs, and was informed that there is basically zero chance that something like this might ever be fixed in S4. 
You can probably imagine how long it took to recode mlr from S4 into S3. I will never go back to S4. 
Maybe one day we will look at R6. But you probably have to convince my uni to give me one semester off teaching, so we can rewrite mlr in this.

But to the point: What is the best option to help with the naming problem?

@larskotthoff @mllg

**Comment by larskotthoff** [comment] 2015-12-21 16:20
I would be careful with allowing more liberal column names. Even though R itself may be fine with it, we support packages like RWeka which are probably a lot pickier. It's not an option to allow names that don't work for everything.

@sanmai-NL If you could demonstrate that a more liberal set of characters is fine, we could consider this. Have a look at the data frames we use in the unit tests and play around with the column names for those -- all the learner tests still need to pass.

**Comment by berndbischl** [comment] 2015-12-21 16:23
Well, one thing I had in mind is to let the user disable this check, but be blunt about it and mention the possible downside that this might break further down below. And we are not fixing around this in every corner of R or integrated package.

**Comment by berndbischl** [comment] 2015-12-21 16:26
@sanmai-NL 
Just as a side note: I have been part of multiple "language crossing" ML projects where always this topic appeared. I usually voted for "conservative naming schemes" +  "well-defined and documented pre-checks". Sometimes I was convinced that being more liberal would be better and easier. It never was. Weird stuff then popped up later and code broke. Always.

**Comment by berndbischl** [comment] 2015-12-21 16:37
Another thing regarding your example: In many cases the feature names have to be put into formulas, either on the LHS or RHS.
(Note: I did not invent this, this is kinda an "R choice" that I also struggle with).

Now imagine these chars to be in your feature:
<SPACE>, +, ~, ..., and so on.
Then what?

**Comment by mllg** [comment] 2016-01-04 09:43
Also note that `af..` is an allowed column name:

```{r}
data = data.frame(target = 1:3, "af.." = 1:3)
makeClassifTask(data = data, target = "target")
makeClassifTask(data = data, target = "af..")
```

@berndbischl Instead of `checkColumnNames()` we could also use `assertDataFrame(..., names = "strict")`.

**Comment by berndbischl** [comment] 2016-01-04 20:04
> Instead of checkColumnNames() we could also use assertDataFrame(..., names = "strict")

You mean to reduce code in mlr and make the check run faster? OK with me.

In general: Have we reached some kind of an conclusion here? Do we want to give users an option to remove the strictness check on names?

**Comment by sanmai-NL** [comment] 2016-01-04 21:39
I'm not commenting further until I have time for it (in a few weeks). I do think some further discussion is still useful by the way. In case you wish to close the ticket, could you perhaps wait?

**Comment by berndbischl** [comment] 2016-01-04 21:54
I have no problem keeping the ticket open for longer, if you need some time. 

Just give us some feedback at SOME point please.

**Closed** 2016-02-11 10:25 UTC
Labels: question

**Comment by jzzcutler** [comment] 2017-10-07 17:26
I had this same problem.  The fix was to use mlr::train.
