### ISSUE TITLE
Tests fail for 'featsel'

### ISSUE THREAD

**Issue by MasonGallo** [mlr-org/mlr#872] opened 2016-05-05 17:46 UTC
I just setup my dev environment on a new mac with a fresh copy of mlr cloned this morning to fix #815 . Running the test for featsel below fails:

`devtools::test(filter = "featsel")`

The first failed dialog is - looks like it has to do with how filterFeatures is called:

```
1. Error: filterFeatures (@test_featsel_filterFeatures.R#5) ----------------------------
An error has occurred in the grow algorithm.  Please turn trace on for further analysis.
1: filterFeatures(binaryclass.task, select = "threshold", threshold = -Inf) at /Users/mason/projects/mlr/tests/testthat/test_featsel_filterFeatures.R:5

```
Is this reproducible on other machines?

Output of R.version on my local machine:

```
platform      x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.0                         
year           2016                        
month          05                          
day            03                          
svn rev        70573                       
language       R                           
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational
```

**Comment by schiffner** [comment] 2016-05-05 18:28
Hi,

I couldn't reproduce on my mac, but I'm still on R 3.2.4. Updating now.

When running the featsel tests do you see only the one error you posted, or are there more?

**Comment by MasonGallo** [comment] 2016-05-05 18:37
Thanks! I only posted a snippet to avoid the wall of text in case it was something obvious. I will look into testing on another machine/VM. The full output is below:

```
analyzeFeatSelResult: ..
FeatSelWrapper: ...
filterFeatures: <simpleError in .Call("rfsrcGrow", as.integer(do.trace), as.integer(seed), as.integer(impute.only.bits +     var.used.bits + split.depth.bits + importance.bits + bootstrap.bits +     forest.bits + proximity.bits + split.null.bits + perf.bits +     membership.bits + statistics.bits), as.integer(0 + na.action.bits +     fast.restore.bits + split.cust.bits), as.integer(splitinfo$index),     as.integer(splitinfo$nsplit), as.integer(mtry), as.integer(if (is.na(formulaDetail$ytry)) 0 else formulaDetail$ytry),     as.integer(nodesize), as.integer(nodedepth), as.double(cause.wt),     as.integer(ntree), as.integer(n), as.integer(length(yvar.types)),     as.character(yvar.types), as.integer(yvar.nlevels), as.double(as.vector(yvar)),     as.integer(n.xvar), as.character(xvar.types), as.integer(xvar.nlevels),     as.double(xvar.wt), as.double(xvar), as.integer(length(event.info$time.interest)),     as.double(event.info$time.interest), as.double(miss.tree),     as.integer(nimpute), as.integer(get.rf.cores())): "rfsrcGrow" not resolved from current namespace (randomForestSRC)>
1<simpleError in .Call("rfsrcGrow", as.integer(do.trace), as.integer(seed), as.integer(impute.only.bits +     var.used.bits + split.depth.bits + importance.bits + bootstrap.bits +     forest.bits + proximity.bits + split.null.bits + perf.bits +     membership.bits + statistics.bits), as.integer(0 + na.action.bits +     fast.restore.bits + split.cust.bits), as.integer(splitinfo$index),     as.integer(splitinfo$nsplit), as.integer(mtry), as.integer(if (is.na(formulaDetail$ytry)) 0 else formulaDetail$ytry),     as.integer(nodesize), as.integer(nodedepth), as.double(cause.wt),     as.integer(ntree), as.integer(n), as.integer(length(yvar.types)),     as.character(yvar.types), as.integer(yvar.nlevels), as.double(as.vector(yvar)),     as.integer(n.xvar), as.character(xvar.types), as.integer(xvar.nlevels),     as.double(xvar.wt), as.double(xvar), as.integer(length(event.info$time.interest)),     as.double(event.info$time.interest), as.double(miss.tree),     as.integer(nimpute), as.integer(get.rf.cores())): "rfsrcGrow" not resolved from current namespace (randomForestSRC)>
2
FilterWrapper: ..........
selectFeatures: ..................

Failed ---------------------------------------------------------------------------------
1. Error: filterFeatures (@test_featsel_filterFeatures.R#5) ----------------------------
An error has occurred in the grow algorithm.  Please turn trace on for further analysis.
1: filterFeatures(binaryclass.task, select = "threshold", threshold = -Inf) at /Users/mason/projects/mlr/tests/testthat/test_featsel_filterFeatures.R:5
2: generateFilterValuesData(task = task, method = method, nselect = nselect, ...) at /Users/mason/projects/mlr/R/filterFeatures.R:45
3: lapply(filter, function(x) {
       x = do.call(x$fun, c(list(task = task, nselect = nselect), list(...)))
       missing.score = setdiff(fn, names(x))
       x[missing.score] = NA_real_
       x[match(names(x), fn)]
   }) at /Users/mason/projects/mlr/R/generateFilterValues.R:53
4: FUN(X[[i]], ...)
5: do.call(x$fun, c(list(task = task, nselect = nselect), list(...))) at /Users/mason/projects/mlr/R/generateFilterValues.R:54
6: (function (task, nselect, ...) 
   {
       im = randomForestSRC::rfsrc(getTaskFormula(task), data = getTaskData(task), proximity = FALSE, 
           forest = FALSE, importance = "permute", ...)$importance
       if (inherits(task, "ClassifTask")) {
           ns = rownames(im)
           y = im[, "all"]
       }
       else {
           ns = names(im)
           y = unname(im)
       }
       setNames(y, ns)
   })(task = structure(list(type = "classif", env = <environment>, weights = NULL, blocking = NULL, 
       task.desc = structure(list(id = "binary", type = "classif", target = "Class", size = 208L, 
           n.feat = structure(c(60L, 0L, 0L), .Names = c("numerics", "factors", "ordered")), 
           has.missings = FALSE, has.weights = FALSE, has.blocking = FALSE, class.levels = c("M", 
           "R"), positive = "M", negative = "R"), .Names = c("id", "type", "target", "size", 
       "n.feat", "has.missings", "has.weights", "has.blocking", "class.levels", "positive", 
       "negative"), class = c("TaskDescClassif", "TaskDescSupervised", "TaskDesc"))), .Names = c("type", 
   "env", "weights", "blocking", "task.desc"), class = c("ClassifTask", "SupervisedTask", "Task"
   )), nselect = 60L, select = "threshold")
7: randomForestSRC::rfsrc(getTaskFormula(task), data = getTaskData(task), proximity = FALSE, 
       forest = FALSE, importance = "permute", ...) at /Users/mason/projects/mlr/R/Filter.R:146
8: stop("An error has occurred in the grow algorithm.  Please turn trace on for further analysis.")

2. Error: plotFilterValues (@test_featsel_filterFeatures.R#86) -------------------------
An error has occurred in the grow algorithm.  Please turn trace on for further analysis.
1: generateFilterValuesData(binaryclass.task, method = c("chi.squared", "rf.importance")) at /Users/mason/projects/mlr/tests/testthat/test_featsel_filterFeatures.R:86
2: lapply(filter, function(x) {
       x = do.call(x$fun, c(list(task = task, nselect = nselect), list(...)))
       missing.score = setdiff(fn, names(x))
       x[missing.score] = NA_real_
       x[match(names(x), fn)]
   }) at /Users/mason/projects/mlr/R/generateFilterValues.R:53
3: FUN(X[[i]], ...)
4: do.call(x$fun, c(list(task = task, nselect = nselect), list(...))) at /Users/mason/projects/mlr/R/generateFilterValues.R:54
5: (function (task, nselect, ...) 
   {
       im = randomForestSRC::rfsrc(getTaskFormula(task), data = getTaskData(task), proximity = FALSE, 
           forest = FALSE, importance = "permute", ...)$importance
       if (inherits(task, "ClassifTask")) {
           ns = rownames(im)
           y = im[, "all"]
       }
       else {
           ns = names(im)
           y = unname(im)
       }
       setNames(y, ns)
   })(task = structure(list(type = "classif", env = <environment>, weights = NULL, blocking = NULL, 
       task.desc = structure(list(id = "binary", type = "classif", target = "Class", size = 208L, 
           n.feat = structure(c(60L, 0L, 0L), .Names = c("numerics", "factors", "ordered")), 
           has.missings = FALSE, has.weights = FALSE, has.blocking = FALSE, class.levels = c("M", 
           "R"), positive = "M", negative = "R"), .Names = c("id", "type", "target", "size", 
       "n.feat", "has.missings", "has.weights", "has.blocking", "class.levels", "positive", 
       "negative"), class = c("TaskDescClassif", "TaskDescSupervised", "TaskDesc"))), .Names = c("type", 
   "env", "weights", "blocking", "task.desc"), class = c("ClassifTask", "SupervisedTask", "Task"
   )), nselect = 60L)
6: randomForestSRC::rfsrc(getTaskFormula(task), data = getTaskData(task), proximity = FALSE, 
       forest = FALSE, importance = "permute", ...) at /Users/mason/projects/mlr/R/Filter.R:146
7: stop("An error has occurred in the grow algorithm.  Please turn trace on for further analysis.")

DONE ===================================================================================
```

**Comment by berndbischl** [comment] 2016-05-05 18:50
hi.

1) does this really happen in a feshly started R? when you run the test for featsel as the first thing?

2) can you please also try to install rt
https://github.com/rdatsci/rt
then run on the console
rtest --filter=featsel

**Comment by schiffner** [comment] 2016-05-05 18:52
Thx.

So I updated R (freshly started) and ran the featsel  tests. I seem to have problems with RWeka and java (I'm seeing this several times: `java.lang.UnsupportedClassVersionweka/core/Attribute : Unsupported major.minor version 51.0`), but I couldn't reproduce the error you saw with randomForestSRC.

**Comment by berndbischl** [comment] 2016-05-05 18:59
(my post was for Mason)

So, I have seen this error before. Mainly when i ran a couple of tests in row. 
Or calling load_all a couple of times. 
Restarting R always fixed it for me, so I assumed a was a weird thing in combo with randomForestSRC and devtools.

**Comment by berndbischl** [comment] 2016-05-05 19:02
and to be honest, because of the "instability" of randomForestSRC and stuff like this here, I really dislike the fact that we use this package in rf.importance. Its only advantage is that we can run this on survival data. 

I guess we might discuss going back to the normal "randomForest" again?

**Comment by larskotthoff** [comment] 2016-05-05 19:09
So we have tests on R-devel with all the latest packages that should flag this up, so it's likely something specific to your environment. Did you install the github version of mlr?

@schiffner Your JVM is too old.

**Comment by schiffner** [comment] 2016-05-05 19:11
> (my post was for Mason)

I know. Just wanted to give this info, too, in case it was important, which it seems to be...

> and to be honest, because of the "instability" of randomForestSRC and stuff like this here, I really dislike the fact that we use this package in rf.importance. Its only advantage is that we can run this on survival data.

> I guess we might discuss going back to the normal "randomForest" again?

Do you have any more specific info on problems with randomForestSRC? As I'm still mailing with the maintainers because of the learner interfaces I could mention this, too. So far they were pretty fast in fixing things.

But if problems persist after the next randomForestSRC release going back to randomForest sounds reasonable.

@larskotthoff : Thanks

**Comment by MasonGallo** [comment] 2016-05-05 19:12
I initially ran in a freshly installed R, but I had ran `devtools::test(filter = "base")` first. 

If I close and reinitialize R, the test passes if it's the first test ran. However, if I run more than 1 test in sequence, I reproduce the same issue.

**Comment by berndbischl** [comment] 2016-05-05 19:15
Julia:
> I know. Just wanted to give this info, too, in case it was important, which it seems to be...

Sure :)



> If I close and reinitialize R, the test passes if it's the first test ran. However, if I run more than 1 test in sequence, I reproduce the same issue.

Thats exactly what I meant and have experienced. And I think this only happens because we load stuff via devtools and load_all. But I have no clue why this happens.

It is quite annoying but you can deal with it?

**Comment by MasonGallo** [comment] 2016-05-05 19:19
Thanks all! I can work around it for now - just wanted to make sure there wasn't something wrong with my local machine.

Thanks for reminding me about rt. I think that's the easiest way to avoid the issue by calling from the command line for now.

**Comment by berndbischl** [comment] 2016-05-05 19:20
about rt: strong yes.

are you on hangout?

**Comment by MasonGallo** [comment] 2016-05-05 19:22
Yes, my username is my gmail

**Comment by berndbischl** [comment] 2016-05-05 19:23
ah, sorry posted too quickly.

1) about rt: yes, use this to run the "longer batches" of tests.

2) in general dont run all unit tests without a filter. we simply have too many of them. filter first to relevant files. then later to the group you are working on. for all tests in a row I guess its best to let that run on travis / jenkins. 

3) i see that your test breaks in test_featsel_filter in lines 5 and 86. you could simply try to change the filter "method" there. it actually does not really matter what we use there. it chaning to another method there makes it more stable you could do a PR.

**Comment by berndbischl** [comment] 2016-05-05 20:10
> 3) i see that your test breaks in test_featsel_filter in lines 5 and 86. you could simply try to change the filter "method" there. it actually does not really matter what we use there. it chaning to another method there makes it more stable you could do a PR.

Mason and I spoke on Hangout. Mason will try to do a PR to change these 2 lines. Then we can close here.

**Comment by berndbischl** [comment] 2016-06-15 00:54
@MasonGallo 
my last post said you wanted to do a PR? where is it?

**Comment by berndbischl** [comment] 2016-06-15 01:06
i changed these lines now myself, so i can close this here

**Comment by MasonGallo** [comment] 2016-06-15 01:11
I never submitted a PR because I wasn't sure what the real source of the problem was. For the record, I still don't understand what caused the original bug.

**Comment by berndbischl** [comment] 2016-06-15 01:15
i dont understand it either, 100%. but it is somewhat "weird" in randomForestSRC, possibly in conjuction with loading mlr via load_all from devtools. 
which requires you to restart your R session.

my fix was to rely less on randomForestSRC in the unit test lines i mentioned.

**Comment by berndbischl** [comment] 2016-06-15 01:16
(what i understand is that the facts given in the post above are true, and i have seen this and suffered from the forced restart by rfSRC many times)

**Comment by MasonGallo** [comment] 2016-06-15 02:08
I still seem to get the error when running the tests in sequence, this time coming from line 13...let me see if I can fix really quick

**Comment by berndbischl** [comment] 2016-06-15 02:11
you can quickly check, but please note that it is very unlikely you can get rid of this 100%.
as that would mean NEVER to trigger rf.importance, which is our default method in filterFeatures.

**Comment by MasonGallo** [comment] 2016-06-15 02:14
Yes I completely agree - I did a PR but we probably won't want to use it for that reason. I suppose we will just have to live with this for now.

**Closed** 2016-06-15 02:27 UTC
