### ISSUE TITLE
Hyper-parameters at predict time?

### ISSUE THREAD

**Issue by mazgit82** [mlr-org/mlr#2044] opened 2017-10-25 18:24 UTC
Adjusting hyper-parameters usually involves training a different model for each hyper-parameter value (u.e. maxdepth for decision trees). However, for some methods (gbm, xgboost), it is possible to train a model with a large number of trees (let's say 1000), but restrict the number of trees to be used at predict time (with predict(gbm_model, n.trees = x) or predict(xgb_model, ntreelimit = x)). 

This saves time, because if you intend to select the optimal number of trees among {100, 200, 300, ..., 1000}, the ensemble model (with 1000 trees) needs to be trained just once, and then test the different hyper-parameter values when using predict. Would it be possible to define a hyper-parameter property, or a new type of hyper-parameter, so that no longer require training a new model each time, but rather testing them at predict time? 

I believe this could be also useful for filter wrappers, since you need to evaluate and rank features just once, and then determine the optimal number of features (the fw.abs hyper-parameter) at predict time (rather than having to evaluate all the features for each fw.abs value (select 1 feature, select 2 features, select 3 features, and so on).

**Comment by jakob-r** [comment] 2017-10-26 07:40
This is a duplicate of #223.
Further discussion in #298.

In other words this is quite complicated to implement at the momentary state but we have this in mind for future mlr versions.

**Closed by jakob-r** 2017-10-26 07:40 UTC
