### ISSUE TITLE
getParamSet of xgboost does not work

### ISSUE THREAD

**Issue by ja-thomas** [mlr-org/mlr#1292] opened 2016-10-17 08:11 UTC
```
> getParamSet("classif.xgboost")
Error in data.frame(Type = x$type, len = len, Def = def, Constr = constr,  : 
  arguments imply differing number of rows: 1, 0
```

I think this may have to do with an update of CRAN xgboost

**Comment by PhilippPro** [comment] 2016-10-17 09:32
I have also seen this and was disappointed (sry, for not posting it).

**Comment by schiffner** [comment] 2016-10-17 12:30
I think the problem is with printing parameter sets with parameters whose defaults have been set to `default = NULL`.

The traceback shows:
```
getParamSet("classif.xgboost")
Error in data.frame(Type = x$type, len = len, Def = def, Constr = constr,  : 
  arguments imply differing number of rows: 1, 0

Enter a frame number, or 0 to exit   

1: function (x, ...) 
UseMethod("print")(x)
2: print.ParamSet(x)
3: print(getParSetPrintData(x, trafo = trafo, used = used, constr.clip = const
4: getParSetPrintData(x, trafo = trafo, used = used, constr.clip = constr.clip
5: lapply(x$pars, getParPrintData, trafo = trafo, used = used, constr.clip = c
6: FUN(X[[i]], ...)
7: data.frame(Type = x$type, len = len, Def = def, Constr = constr, Req = ifel

Selection: 6
Called from: eval(substitute(browser(skipCalls = skip), list(skip = 7 - which)), 
    envir = sys.frame(which))

## responsible parameter
Browse[1]> x$id
[1] "missing"

## its default
Browse[1]> def
character(0)
```

**Comment by berndbischl** [comment] 2016-12-16 01:34
fixed in PH now. unit test is dicussed in issue #1352

**Closed by berndbischl** 2016-12-16 01:34 UTC
Labels: bug, prio-high
