### ISSUE TITLE
getBMRModels - the returned model objects look very different to the type of object returned by the train function. How to get the same structure as the train function from a benchmark experiment?

### ISSUE THREAD

**Issue by mlearner-jl** [mlr-org/mlr#2215] opened 2018-03-12 10:51 UTC
Minimal Working Example:

```
library(mlr)
library(mlbench)

trainData = data(BreastCancer)
trainData = BreastCancer
rm(Breastcancer)

target_column_name = "Class"

classif_xgboost = makeLearner("classif.xgboost", predict.type="prob")
###One-Hot Encoding
classif_xgboost = makeDummyFeaturesWrapper(classif_rforest, method = "1-of-n")

classif_rforest = makeLearner("classif.randomForestSRC", predict.type="prob")
###One-Hot Encoding
classif_rforest = makeDummyFeaturesWrapper(classif_rforest, method = "1-of-n")


trainData[[target_column_name]] = as.factor(trainData[[target_column_name]])

drops <- c("Id")
trainData = trainData[ , !(names(trainData) %in% drops)]

training_task_name = "BreastcancerTrain"
positive_target = "malignant"
trainTask = makeClassifTask(id=training_task_name, data=trainData, target=target_column_name, positive=positive_target, fixup.data="warn", check.data=TRUE)

valid_indices = seq(88, 100)
train_indices = seq(1, 87)
outer_resampling = makeFixedHoldoutInstance(train_indices, valid_indices, nrow(getTaskData(trainTask)))

res1 = benchmark(tasks = trainTask, learners = classif_xgboost, resampling = outer_resampling, measures = list(logloss, auc, f1, ber, acc, bac, mmce, timetrain), show.info = TRUE)
res2 = benchmark(tasks = trainTask, learners = classif_rforest, resampling = outer_resampling, measures = list(logloss, auc, f1, ber, acc, bac, mmce, timetrain), show.info = TRUE)

benchmark_results = mergeBenchmarkResults(list(res1, res2))

getBMRPerformances(benchmark_results, as.df=TRUE)

models <- getBMRModels(benchmark_results, drop = TRUE)

xgb_model = train(classif_xgboost, trainTask)
rf_model = xgb_model = train(classif_rforest, trainTask)

names(xgb_model)
Minimal Working Example
library(mlr)
library(mlbench)

trainData = data(BreastCancer)
trainData = BreastCancer
rm(Breastcancer)

target_column_name = "Class"

classif_xgboost = makeLearner("classif.xgboost", predict.type="prob")
###One-Hot Encoding
classif_xgboost = makeDummyFeaturesWrapper(classif_rforest, method = "1-of-n")

classif_rforest = makeLearner("classif.randomForestSRC", predict.type="prob")
###One-Hot Encoding
classif_rforest = makeDummyFeaturesWrapper(classif_rforest, method = "1-of-n")


trainData[[target_column_name]] = as.factor(trainData[[target_column_name]])

drops <- c("Id")
trainData = trainData[ , !(names(trainData) %in% drops)]

training_task_name = "BreastcancerTrain"
positive_target = "malignant"
trainTask = makeClassifTask(id=training_task_name, data=trainData, target=target_column_name, positive=positive_target, fixup.data="warn", check.data=TRUE)

valid_indices = seq(88, 100)
train_indices = seq(1, 87)
outer_resampling = makeFixedHoldoutInstance(train_indices, valid_indices, nrow(getTaskData(trainTask)))

res1 = benchmark(tasks = trainTask, learners = classif_xgboost, resampling = outer_resampling, measures = list(logloss, auc, f1, ber, acc, bac, mmce, timetrain), show.info = TRUE)
res2 = benchmark(tasks = trainTask, learners = classif_rforest, resampling = outer_resampling, measures = list(logloss, auc, f1, ber, acc, bac, mmce, timetrain), show.info = TRUE)

benchmark_results = mergeBenchmarkResults(list(res1, res2))

getBMRPerformances(benchmark_results, as.df=TRUE)

models <- getBMRModels(benchmark_results, drop = TRUE)

xgb_model = train(classif_xgboost, trainTask)
rf_model = train(classif_rforest, trainTask)

names(xgb_model)
```

How do I extract the models from the Benchmark Results object to have the same structure as the object returned from the train function?

I rely on this object structure to extract information about the model etc.

**Comment by jakob-r** [comment] 2018-03-12 15:52
Please do not crosspost. This is duplicate of the question asked on [SO](https://stackoverflow.com/questions/49233822/mlr-getbmrmodels-the-returned-model-objects-very-different-to-object-returne).
Have you tried the answer given there?

**Closed by jakob-r** 2018-03-12 15:52 UTC

**Comment by mlearner-jl** [comment] 2018-03-12 18:19
Apologies for the crosspost. No that suggestion does not work.
