### ISSUE TITLE
Hyperparameter effects data and plot: only subsets shown

### ISSUE THREAD

**Issue by eddelbuettel** [mlr-org/mlr#1287] opened 2016-10-13 19:21 UTC
I am getting weird results from `plotHyperParsEffect()`. Here is a variant.  The grid is 3 x 3, but the plot 
omits two `ntree` values and and one `mtry` value.  That may be on purpose for lack of variability in the outcome -- if so, could we signal more clearly?

```
    paramset <- makeParamSet(makeDiscreteParam("ntree", values=c(100,500,1000)),
                             makeDiscreteParam("mtry", values=c(1,3,5)))
    ctrl <- makeTuneControlGrid()
    rdesc <- makeResampleDesc("CV", iters = 5L)
    learn <- makeLearner("classif.randomForest", predict.type="prob")
    lrn <- makeTuneWrapper(learn,
                           control = ctrl,
                           measures = list(acc, mmce),
                           resampling = rdesc,
                           par.set = paramset,
                           show.info = TRUE)
    res <- resample(lrn,
                    task = pid.task,
                    resampling = rdesc,
                    extract = getTuneResult,
                    show.info = TRUE)
    data <- generateHyperParsEffectData(res, partial.dep=TRUE)
    plt <- plotHyperParsEffect(data,
                               x = "ntree", #"nrounds",
                               y = "mtry",
                               z = "acc.test.mean",
                               plot.type = "heatmap",
                               show.experiments = TRUE,
                               nested.agg = mean,
                               partial.dep.learn = "regr.earth")  
    print(plt)
```

**Comment by MasonGallo** [comment] 2016-10-13 21:47
Thanks for submitting this. 

I would argue that you don't have enough data to "do" partial dependence here: you're attempting to learn a regression function over 2 features with essentially 9 observations. Based on your previous discussion, I think I'm preachign to the choir here :)

What's happening is partial dependence under the hood range is getting tripped up with integers. Looks like the problem is with `generatePartialDependenceData` not `plotHyperParsEffect`. I have an idea for a quick fix which I should get to tonight, assuming it doesn't break anything else.

Thoughts anyone else?

**Comment by schiffner** [comment] 2016-10-13 22:45
Agree with your conclusion. Let me or Zach know if we can help.

**Comment by schiffner** [comment] 2016-10-13 23:27
Maybe one more thought.
It would be nice to have faceting also for heat maps, in cases were we have a small parameter grid or some parameters with few values, but in total > 2 hyper pars (i.e, the case where at the moment the only way is partial dependence, but fitting a regression model might not work that well). Does that make sense?

**Comment by MasonGallo** [comment] 2016-10-14 02:25
Julia - I'm not sure what you mean. Can you show an example?

**Comment by eddelbuettel** [comment] 2016-10-14 02:29
I understood the suggestion to be in the spirit of this [StackOverflow example](http://stackoverflow.com/questions/33987459/how-to-create-facet-heatmap-ggplot2).

**Comment by MasonGallo** [comment] 2016-10-14 02:58
Got it. Something similar to this is on my longer term roadmap along with a few other features. It will likely take a bit of refactoring for the non grid search usecase. PRs are always welcome of course.

Just curious - would this be something you two would use a lot? I did not envision this use when originally prototyping.

**Comment by eddelbuettel** [comment] 2016-10-14 03:09
Hard to say. I could have used it today when working with XGBoost.  For randomForest and its fewer parameters, less so.

**Comment by zmjones** [comment] 2016-10-14 13:39
I mentioned this in https://github.com/mlr-org/mlr/pull/1289, and @MasonGallo basically said the same thing, but the issue isn't the use of partial dependence per say, but trying to fit a model to so little training data. I think it would be fine to warn users about that, but that belongs in the hyperpar effect functions not partial dependence or the prediction grid generation functions.

**Comment by MasonGallo** [comment] 2016-10-14 14:16
Agreed. I will do a PR soon to add a warning to hyperpar effects.

**Comment by MasonGallo** [comment] 2016-10-14 14:17
The bug here is merged and @zmjones is working on an additional slightly related PR. 

If you're interested in discussing faceting for hyperparameter effects, please open a separate issue.

**Closed by MasonGallo** 2016-10-14 14:17 UTC
Labels: bug, prio-high
