### ISSUE TITLE
extract argument is missing in several resampling functions

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#462] opened 2015-09-03 08:07 UTC
In the `resample` function, we have a `extract` argument. This should also be included in the `benchmark` function and the `crossval`, `repcv` ... functions.

**Comment by jakob-r** [comment] 2015-09-03 10:06
I think PR #419 is related

**Comment by jakob-r** [comment] 2015-09-03 15:51
I merged PR #419 
We can close this Issue once we agree if testing is sufficient.

**Comment by berndbischl** [comment] 2015-09-04 08:23
Please dont merge.
1) I have now a dozen of your commits in the history, which are very hard to review. for a very basic new feature.
2) you did again not put your chnange into NEWS

:(

**Comment by jakob-r** [comment] 2015-09-04 08:45
[All files changed in the curse of the PR #419 and solving this issue](https://github.com/mlr-org/mlr/pull/419/files).
Just 8 files
:)

**Comment by berndbischl** [comment] 2015-09-22 16:29
@jakob-r 
I can close this because the issue is only about "extract" missing in the helpers like "crossval", etc?
And the other issue we discuss friday?

**Comment by jakob-r** [comment] 2015-09-23 16:31
Exactly.

Bernd Bischl <notifications@github.com> schrieb am Di., 22. Sep. 2015 18:29:

**Comment by berndbischl** [comment] 2015-09-23 16:42
thx

**Comment by giuseppec** [comment] 2016-05-03 07:27
Hm, `extract` is still missing for the `benchmark` function, although in https://github.com/mlr-org/mlr/pull/419/files an `extract` argument was introduced in the `benchmark` function. 
Has this been removed again?
I maybe will need this to be able to extract values for each resample iteration (for the tune traces in OpenML) and we are using the `benchmark` function here, which apparently does not offer this `extract` argument anymore.

**Comment by jakob-r** [comment] 2016-05-03 07:59
Yeah. Somewhere you will find an Issue where @berndbischl  wanted me to redo the changes. Here is the commit.
https://github.com/mlr-org/mlr/commit/548f7ac20773052531ad261d6f4f4aa1b3843911#diff-fa967e86b6fb2ba0f708b87c3d6d2b73

**Comment by giuseppec** [comment] 2016-05-03 08:02
Maybe I found a way where I don't need this, but was there a reason why we don't want the `benchmark` function to support the `extract` arg?

**Comment by jakob-r** [comment] 2016-05-03 08:08
I think it was because it did something new,  not overly well documentedand and @berndbischl was afraid that it breaks something.

**Comment by pat-s** [comment] 2018-10-28 20:46
Cleaning up / closing old issues. I assume that this enhancement is not of interest anymore after all this time. 
Feel free to re-open if s.o. is tackling it again.

**Closed by pat-s** 2018-10-28 20:46 UTC
Labels: prio-medium, project - base, type-enhancement
