### ISSUE TITLE
Error in makeParamSet when tuning hyperparameters of nnet

### ISSUE THREAD

**Issue by vrgaliano** [mlr-org/mlr#1418] opened 2017-01-06 20:44 UTC
```r 
data(BostonHousing, package = "mlbench")
regr.task = makeRegrTask(id = "bh", data = BostonHousing, target = "medv")

#tuning hyperparameters
ps.nnet = makeParamSet(
makeDiscreteParam("size", values = seq(1, 10, by=1)),  
makeDiscreteParam("decay", values = seq(0, 0.1, by=0.005)),
     )

Error in makeParamSet(makeDiscreteParam("size", values = seq(1, 10, by = 1)),  : 
  argument is missing, with no default
```

**Comment by schiffner** [comment] 2017-01-06 20:58
Hi,

please remove the comma at the end of the line starting with `makeDiscreteParam("decay", ...`. It should work then.
I'm closing this issue. Please feel free to reopen if you encounter any further problems.

**Comment by vrgaliano** [comment] 2017-01-06 21:02
Dear Julia,

thanks for your prompt reply. I does not work after removing the comma:

Error in makeIntegerParam("size", values = seq(1, 10, by = 1)) :
  unused argument (values = seq(1, 10, by = 1))

2017-01-06 21:58 GMT+01:00 Julia Schiffner <notifications@github.com>:

**Comment by schiffner** [comment] 2017-01-06 21:20
Hi,

could you please check if this works for you?

```
data(BostonHousing, package = "mlbench")
regr.task = makeRegrTask(id = "bh", data = BostonHousing, target = "medv")
 
#tuning hyperparameters
ps.nnet = makeParamSet(
  makeDiscreteParam("size", values = seq(1, 10, by=1)),
  makeDiscreteParam("decay", values = seq(0, 0.1, by=0.005))
)
```

**Comment by vrgaliano** [comment] 2017-01-06 21:44
Dear Julia,

it does work. Many thanks

2017-01-06 22:20 GMT+01:00 Julia Schiffner <notifications@github.com>:

**Comment by vrgaliano** [comment] 2017-01-06 22:26
The learner gives an error when training with the selected hyper-parameters:

data(BostonHousing, package = "mlbench")
regr.task = makeRegrTask(id = "bh", data = BostonHousing, target = "medv")

#tuning hyperparameters
ps.nnet = makeParamSet(
  makeDiscreteParam("size", values = seq(1, 10, by=1)),
  makeDiscreteParam("decay", values = seq(0, 0.1, by=0.005))


ctrl = makeTuneControlGrid()
rdesc = makeResampleDesc("CV", iters = 10)
res = tuneParams("regr.avNNet", task = regr.task, resampling = rdesc,
par.set = ps.nnet,
  control = ctrl)
lrn.nnet = setHyperPars(makeLearner("regr.avNNet"), par.vals = res$x)
m = train(lrn.nnet, regr.task)

Error in unique.default(x, nmax = nmax) :
  unique() applies only to vectors


2017-01-06 22:44 GMT+01:00 Victor F. Rodriguez Galiano <vrgaliano@gmail.com>
:

**Comment by schiffner** [comment] 2017-01-06 22:57
Hi,

I just tried a very reduced version of your example which worked for me.
Could you please include more information, most importantly a traceback? Do you get the error every time? For which values of `res$x` does the error occur?

**Comment by vrgaliano** [comment] 2017-01-06 23:52
I have tried to run the code with different ranges of parameters, but I get
the same error always:

 lrn.nnet = setHyperPars(makeLearner("regr.avNNet"), par.vals = res$x)
>     m = train(lrn.nnet, regr.task)
Error in unique.default(x, nmax = nmax) :
  unique() applies only to vectors
>
> res$x
$size
[1] 7

$decay
[1] 0.04


2017-01-06 23:57 GMT+01:00 Julia Schiffner <notifications@github.com>:

**Comment by schiffner** [comment] 2017-01-09 12:21
Unfortunately, I can't reproduce.
* Which versions of packages mlr, ParamHelpers, nnet are you using?
* Could you please run `traceback()` after the error occurs and post the result?
Thanks very much.

**Comment by vrgaliano** [comment] 2017-01-09 14:54
> m = train(lrn.nnet, regr.task)
Error in unique.default(x, nmax = nmax) :
  unique() applies only to vectors
> traceback()
6: unique.default(x, nmax = nmax)
5: unique(x, nmax = nmax)
4: factor(a, exclude = exclude)
3: table(y)
2: train.default(lrn.nnet, regr.task)
1: train(lrn.nnet, regr.task)
> print(version)
               _
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
system         x86_64, mingw32
status
major          3
minor          2.3
year           2015
month          12
day            10
svn rev        69752
language       R
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree


nnet version: 7.3-11
mlr version: 2.9

2017-01-09 13:21 GMT+01:00 Julia Schiffner <notifications@github.com>:

**Comment by schiffner** [comment] 2017-01-09 15:38
Many thanks.
It seems that you also loaded package caret? I can reproduce the error if I run `caret::train` instead of `mlr::train`.
(In order to make sure that you run the mlr functions please always load mlr last.)

**Comment by vrgaliano** [comment] 2017-01-09 16:04
Dear Julia,

I think the problem was to load caret package after mlr. It does work now.
Thank you very much.

2017-01-09 16:38 GMT+01:00 Julia Schiffner <notifications@github.com>:

**Comment by schiffner** [comment] 2017-01-09 16:11
Dear Victor,

great it's working now.

Best,
Julia

**Closed by schiffner** 2017-01-09 16:11 UTC

**Comment by zmosleh** [comment] 2017-08-26 06:35
Error in unique.default(x, nmax = nmax) :   unique() applies only to vectors
Dear schiffner
i want to do synthetic minority oversampling technique (SMOTE) using dmwr package but i get the following error:
Error in unique.default(x, nmax = nmax) :   unique() applies only to vectors
i use the mlr::train.
> traceback()
6: unique.default(x, nmax = nmax)
5: unique(x, nmax = nmax)
4: factor(a, exclude = exclude)
3: table(data[, tgt])
2: which.min(table(data[, tgt]))
1: SMOTE(gg ~ dem + slope, data = data, percOver = 600, percUnder = 100, 
       learner = "rpartXse", se = 0.5)
> print (version)
               _                           
platform       i386-w64-mingw32            
arch           i386                        
os             mingw32                     
system         i386, mingw32               
status                                     
major          3                           
minor          2.3                         
year           2015                        
month          12                          
day            10                          
svn rev        69752                       
language       R                           
version.string R version 3.2.3 (2015-12-10)
nickname       Wooden Christmas-Tree  
mlr version: 2.11
if possible please help me.
