### ISSUE TITLE
ranger bug

### ISSUE THREAD

**Issue by giuseppec** [mlr-org/mlr#1229] opened 2016-09-09 13:01 UTC
``` r
ksdata = read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/chess/king-rook-vs-king-pawn/kr-vs-kp.data")

# task has no missings
kstask = makeClassifTask(data = ksdata, target = "won")

lrn = makeLearner("classif.ranger")
set.seed(1)
cv = crossval(lrn, kstask)
```

This is the result I get, any ideas @mnwright?

```
[Resample] cross-validation iter: 1
[Resample] cross-validation iter: 2
[Resample] cross-validation iter: 3
Error in predict.ranger.forest(forest, data, predict.all, seed, num.threads,  : 
  Missing values in data.
Timing stopped at: 3.69 0.03 3.89
```

**Comment by ja-thomas** [comment] 2016-09-09 14:22
The problem is that one column is almost constant (only one observation with `t`).

Same error:

```
y = sample(c("A", "B"), replace = T, size = 3000)
x = as.factor(c("U", rep("K", times = 2999)))
z = matrix(rnorm(3000*30), nrow = 3000)
d = data.frame(y, x, z)

task = makeClassifTask(data = d, target = "y")
set.seed(1)
cv = crossval(lrn, task)
```

So I would guess that ranger somehow brakes if a constant factor with additional factor lvls is in there, but I could not reproduce the error with ranger. This does work in ranger:

```
y = sample(c("A", "B"), replace = T, size = 3000)
x = factor(c(rep("K", times = 3000)), levels = c("K", "U"))
z = matrix(rnorm(3000*30), nrow = 3000)
d = data.frame(y, x, z)

set.seed(1)
ranger(y ~ ., data = d)

```

**Comment by mnwright** [comment] 2016-09-19 13:49
There was a bug in ranger for new factor levels in prediction. It's fixed in the newest Github version (0.5.5). See also imbs-hl/ranger#116.

**Comment by berndbischl** [comment] 2016-09-19 13:54
@giuseppec @ja-thomas 
can you pls have a look whether the bug vanishes on our side with the ranger GH version?
and do a PR with a unit test

@mnwright 
could you pls ping us here, when the ranger fix hits CRAN?

(its a pleasure to be of service at your ML unit testing platform here ;-) )

**Comment by mnwright** [comment] 2016-10-10 07:22
It's on CRAN now.

**Closed** 2016-11-07 14:52 UTC
