### ISSUE TITLE
RMSE measure names out of the pattern

### ISSUE THREAD

**Issue by rgmantovani** [mlr-org/mlr#721] opened 2016-02-15 15:31 UTC
Hi, 

this is just a simple thing: the rmse (column) name returned by resample is different from the pattern.
For example, if I run this:

```R
library("mlr")

set.seed(1)
regressor = makeLearner("regr.randomForest")
rdesc = makeResampleDesc("CV", iters = 10)
perf = list(mse, rmse, sse, sae, mae, medae, medse, featperc, timetrain, timepredict, timeboth)
ret = resample(learner = regressor, task = bh.task, resampling = rdesc, measures = perf)

ret$aggr
```

it returns:
```
        mse.test.mean        rmse.test.rmse         sse.test.mean 
            10.096075              3.177432            510.783906 
        sae.test.mean         mae.test.mean       medae.test.mean 
           108.580638              2.146450              1.495165 
      medse.test.mean    featperc.test.mean   timetrain.test.mean 
             2.259852              1.000000              0.847200 
timepredict.test.mean    timeboth.test.mean 
             0.010300              0.857500 
```

Just **rmse** is different here. It is just a simple renaming from **_rmse.test.rmse_** to **_rmse.test.mean_** would be the case, I guess.

My sessionInfo:
![screen shot 2016-02-15 at 3 53 45 pm](https://cloud.githubusercontent.com/assets/5933552/13052846/6cd5dc92-d401-11e5-8d8d-6d20a6f137e0.png)

**Comment by schiffner** [comment] 2016-02-15 17:17
Hi,

thanks for the report.

You are right that this is out of pattern, but it's not a bug. The names `mse.test.mean` etc. indicate 1) the performance measure and 2) the aggregation scheme used to combine the performance values from single resampling iterations.
The default aggregation scheme for the root mean square error in mlr is `test.rmse` (which calculates sqrt(mean(rmse.vals.on.test.sets^2))).
You can see this for example by running:

```
print(rmse)
```

If you prefer the usual aggregation by `test.mean` (i.e. mean(rmse.vals.on.test.sets)) you can change that easily using `setAggregation`.

```
rmse$aggr
# Aggregation function: test.rmse

rmse2 = setAggregation(rmse, test.mean)

rmse2$aggr
Aggregation function: test.mean
```

Cheers,
Julia

**Comment by jakob-r** [comment] 2016-02-16 13:05
I think this is very well answered and can be closed.

**Comment by schiffner** [comment] 2016-02-16 13:08
@rgmantovani : Please feel free to reopen if there are further questions.
For now I'm closing.

**Closed by schiffner** 2016-02-16 13:08 UTC
Labels: question
