### ISSUE TITLE
friedmanTestBMR - gives strange error message

### ISSUE THREAD

**Issue by xhudik** [mlr-org/mlr#1262] opened 2016-09-25 11:41 UTC
```{r}
lrns=list(
  lrn.logreg = makeLearner("classif.logreg",predict.type = "prob"),
  lrn.svm = makeLearner("classif.svm",predict.type = "prob")
)
bmr = benchmark(lrns, pid.task)
friedmanTestBMR(bmr)
```
gives confusing and meaningless error message
```{r}
Error in apply(y, 1L, rank) : dim(X) must have a positive length
```
This is especialy confusing for newbies. Not sure whether it can be changed, but the current behavior is not user-friendly

thanks

**Comment by larskotthoff** [comment] 2016-09-25 17:54
Where exactly is this error message coming from? Can you post a complete, reproducible example please?

**Comment by xhudik** [comment] 2016-09-26 08:59
@larskotthoff  - the code I posted is complete. (just add library(mlr)). pid.task is an integarl part of the mlr package

**Comment by larskotthoff** [comment] 2016-09-26 16:55
This looks like a bug in `friedman.test()`.

**Comment by schiffner** [comment] 2016-09-26 17:40
I agree with Lars that `freedom.test` doesn't handle this well.

But in mlr we could improve the arg checks and docs for `friedmanTestsBMR`. It does not make sense to use the Friedman test if there aren't at least results for 2 learners and 2 tasks in the `BenchmarkResult`.

**Comment by larskotthoff** [comment] 2016-10-05 09:46
This should be fixed now. Closing here; please reopen if the issue persists.

**Closed by larskotthoff** 2016-10-05 09:46 UTC
