### ISSUE TITLE
Learners from penalized package seem to be broken

### ISSUE THREAD

**Issue by larskotthoff** [mlr-org/mlr#840] opened 2016-04-19 16:02 UTC
See https://hagakure.cs.ubc.ca:2893/job/mlr/370/console

Unit tests are failing after upgrading the penalized package:

1. Error: regr_penalized_lasso (@test_regr_penalized_lasso.R#24) 
2. Error: regr_penalized_ridge (@test_regr_penalized_ridge.R#25)

**Comment by florianfendt** [comment] 2016-04-22 10:32
@berndbischl
Since I already uploaded quite a big PR on this a while ago I think it might be a good time now to review it and have this fixed.
What do you think?

**Comment by berndbischl** [comment] 2016-04-22 10:33
@florianfendt 
Please quickly link it here. Can you also try to repair the penalized learners now. 
This is completely blocking us

**Comment by florianfendt** [comment] 2016-04-25 08:45
@berndbischl 
https://github.com/mlr-org/mlr/pull/665
will look over it again today!

**Comment by berndbischl** [comment] 2016-04-25 10:27
The problem is that this simple code does not run:

```
library(penalized)
library(mlbench)
data(BostonHousing)

m = penalized(medv ~ ., data = BostonHousing)
p = predict(m, data = BostonHousing[1:10,])
```

output 

```
$unpenalized
response ~ 1
<environment: 0xc5fdc60>

$penalized
medv ~ .
<environment: 0xed22da8>

Error in .local(object, ...) : 
  row counts of "penalized", "unpenalized" and/or "data" do not match
```

One can see that the formula in $unpenalized seems wrong....
I will report this to the maintainer now and add a local fix in mlr.
I also dont get why they dont have unit tests for this....

**Comment by berndbischl** [comment] 2016-04-25 11:01
I mailed the maintiainer Jelle Goeman and he said he would look into this.

**Comment by berndbischl** [comment] 2016-04-25 12:48
new PR is #850

**Comment by berndbischl** [comment] 2016-04-25 20:43
PR is merged. We should leave this open, to remove the FIXMEs from the penalized package. 

If this takes a long time: We can later find the relevant lines where i patch the penfit models by searching for issue number 840 in R and tests files.

**Comment by berndbischl** [comment] 2016-06-15 01:56
who cares. lets close this now.

**Closed by berndbischl** 2016-06-15 01:56 UTC
Labels: broken
