### ISSUE TITLE
Problems with feature selection and threshold tuning: optimal threshold of 0.5 all the time

### ISSUE THREAD

**Issue by leoKampfer** [mlr-org/mlr#2289] opened 2018-06-06 11:15 UTC
Hi all,
I am trying to solve a binary classifaction problem with logistic regression (for example, spam detection). Via nested resampling with cross-validation, I select proper features and (want to) tune the threshold in the inner loop, and evaluate the performance in the outer.

Performing the resampling with ```classif.logreg```, the optimal threshold is exactly 0.5 every time, which seems to be odd. Furthermore, the plot ```ThreholdVsPerformance``` suggest a optimale threhold which is above 0.5.

Can anyone help me to understand why the value is 0.5, please?

#### Minimal reproducible example

(reprex added by @pat-s)

``` r
library(mlr)
#> Loading required package: ParamHelpers
data(spam, package = "kernlab")
task = makeClassifTask(data = spam, target = "type")
# inner loop (tune.threshold = TRUE to allow threshold tuning)
ctrl = makeFeatSelControlRandom(tune.threshold = TRUE, maxit = 5L)
inner = makeResampleDesc("CV", iters = 3)
base = makeLearner("classif.logreg", predict.type = "prob")
learner = makeFeatSelWrapper(base, resampling = inner, control = ctrl,
  show.info = FALSE, measure = mmce)
# outer loop
outer = makeResampleDesc("CV", iters = 3)
res = suppressWarnings(resample(learner, task = task, resampling = outer,
  show.info = FALSE, measures = list(auc, mmce))
)
# results
res$aggr
#>  auc.test.mean mmce.test.mean 
#>     0.96414281     0.09084793
res$pred$threshold
#> nonspam    spam 
#>     0.5     0.5
```

<sup>Created on 2019-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Many thanks.

**Comment by Coorsaa** [comment] 2018-08-01 12:52
as a first small solution, you can run ```tuneThreshold(res$pred)``` on your resample predictions to get the correct threshold.
Unfortunately, something goes wrong within the result aggregation...
if you set ```model = TRUE``` within the ```resample()``` function, you can see, that the threshold tuning is actually done and you can access it via ```res$models[[1]]$learner.model$opt.result$threshold``` (here for the first crossvalidated model).
However, the final threshold is not stored into the resample object under ```res$pred$threshold```...

**Comment by Coorsaa** [comment] 2018-08-17 07:54
Let's open it again to get fixed.

**Comment by pat-s** [comment] 2018-11-14 22:03
@Coorsaa 	Do you have time to fix it?

**Comment by albersonmiranda** [comment] 2020-01-22 22:18
I was about to open an issue about that but it seems to be known. I was expecting the following procedure to store tuned thresholds along with hyperparams:

```
tunecontrol = makeTuneControlGrid(resolution = 3L, tune.threshold = TRUE)
set_cv = makeResampleDesc("CV",iters = 5L)

tuning = tuneParams(learner = model$gamboost, resampling = set_cv, task = train.task, par.set = parametros, control = tunecontrol, measures = acc)
model$gamboost = setHyperPars(model$gamboost, par.vals = tuning$x)
```
But, of course, thresholds are still 50%.

**Comment by albersonmiranda** [comment] 2020-01-22 22:22
Following @Coorsaa comment, how do i store thresholds i've got through 
```
test = predict(train, test.task)
tuneThreshold(test)
$th
[1] 0.8873576

$perf
     mmce 
0.1516854 
```
into `test`?

**Comment by pat-s** [comment] 2020-02-01 14:28
There are two different points in this issue: 

- Extracting the optimized thresholds for each fold 
- Calculating a new optimized threshold on the combined predictions of all folds

---

> as a first small solution, you can run `tuneThreshold(res$pred)` on your resample predictions to get the correct threshold.

The problem is that `tuneThreshold` needs to be called on a `Prediction` object to optimize it given a measure.
This object, containing the predictions from all folds, is only available after the results from all folds have been returned.
Also be aware that the threshold is optimized **on the predictions returned by all folds**.

If this is desired one should call `tuneThreshold(res$pred)` manually IMO as showing a value in `res$pred` might be misleading as it might indicate that it is an aggregated value.
I think this even happened in the initial post as OP was trying to compare the aggregated performance with the threshold.

There is no single optimal threshold value in a CV scenario, only for each single fold (which can be queried via `res$models[[<learnerID>]]$learner.model$opt.result$threshold` as Stefan mentioned.
Essentially it can be seen as an hyperpar optimized in each fold. 
We also do not store tune results in the `$pred` slot.

I do not think that calling `tuneThreshold(res$pred)` has a practical relevance / makes sense since the result should not be used as an input for future trained models: It was derived from merged prediction values of a CV and cannot serve as an optimized threshold for a different model (I might be wrong with this though).

I am thinking about removing the threshold slot from the `ResamplePrediction` container to clear confusion.

If one wants to inspect the values manually, one can 

- calculate an average over all `threshold` slots of the fitted models or 
- call `tuneTreshold` manually on the merged predictions (not recommended)

**Comment by pat-s** [comment] 2020-02-01 14:30
> how do i store thresholds i've got through into `test`

I don't think this a good idea/what you want, see my previous comment.

**Comment by albersonmiranda** [comment] 2020-02-06 20:13
@pat-s i'm not sure if i get it. There's no function implemented to get predictions with thresholds other than default .5? Is that correct?

I thought the point of `tune.threshold = TRUE` in `makeTuneControl...()` was to set thresholds for a specifc model by taking CV average. I guess it makes sense to think about it as a hyperparam to be tuned alongside with the others. It'd be useful to get predictions (for that model only) to be tested on test sample.

**Comment by pat-s** [comment] 2020-02-07 07:01
> @pat-s i'm not sure if i get it. There's no function implemented to get predictions with thresholds other than default .5? Is that correct?

No, `tunethreshold()` works just fine.
The returned value in the `pred` object does simply **not** represent the average of the thresholds of the tuning iterations. It is just a dummy placeholder of the generated `pred` object and has no information.
Hence, nothing is going wrong in the results aggregration. 
This slot should just not exist in a `ResampleResult` object.

Question: Image it would not exist: What would you check for in the `ResampleResult` if you want to look at the tuned thresholds?

**Closed** 2020-02-24 21:12 UTC
Labels: prio-high, project - base, type-bug
