### ISSUE TITLE
getBMRObjects call in nested_resampling tutorial page

### ISSUE THREAD

**Issue by zmjones** [mlr-org/mlr#479] opened 2015-09-15 20:39 UTC
in building the tutorial `nested_resampling.Rmd` fails when calling `getBMRTuneResults` and `getBMRPerformances`.

``` r
## Tuned number of filtered features
getBMRTuneResults(res, as.df = TRUE)

## Performances on individual outer test data sets
getBMRPerformances(res, as.df = TRUE)
```

I tracked the issue to `getBMRObjects` where when `fun` (incorrectly?) returns `NULL`.

The relevant code from the tutorial page is below. 

``` r
lrn = makeFilterWrapper(learner = "regr.lm", fw.method = "chi.squared")
ps = makeParamSet(makeDiscreteParam("fw.abs", values = seq_len(getTaskNFeats(bh.task))))
ctrl = makeTuneControlGrid()
inner = makeResampleDesc("CV", iter = 2)
lrn = makeTuneWrapper(lrn, resampling = inner, par.set = ps, control = ctrl,
  show.info = FALSE)

## Learners
lrns = list(makeLearner("regr.rpart"), lrn)

## Outer resampling loop
outer = makeResampleDesc("Subsample", iter = 3)
res = benchmark(tasks = bh.task, learners = lrns, resampling = outer, show.info = FALSE)

## Tuned number of filtered features
getBMRTuneResults(res, as.df = TRUE)

## Performances on individual outer test data sets
getBMRPerformances(res, as.df = TRUE)
```

**Comment by schiffner** [comment] 2015-09-15 23:44
The reason for this error seems to be that the `getBMR*` functions have not been adapted to the latest changes in `benchmark` (https://github.com/mlr-org/mlr/commit/ad027fb3158a4fec5c845e10e6cc992e7c68d03f).

The default `extract`-function now works recursively and, for the second learner in the benchmark experiment, that is wrapped twice, returns a list of lists, which is not expected by `getBMRTuneResults` and the underlying functions. (`getBMRPerformances` works though.)

```
res$result[[1]][["regr.lm.filtered.tuned"]]$extract
[[1]]
[[1]]$TuneResult
Tune result:
Op. pars: fw.abs=12
mse.test.mean=18.9

[[1]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  


[[2]]
[[2]]$TuneResult
Tune result:
Op. pars: fw.abs=13
mse.test.mean=23.6

[[2]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  


[[3]]
[[3]]$TuneResult
Tune result:
Op. pars: fw.abs=12
mse.test.mean=31.1

[[3]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  
```

`getBMRTuneResults` with `as.df = TRUE` fails.

```
getBMRTuneResults(res, as.df = TRUE)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 3, 0

Enter a frame number, or 0 to exit   

 1: getBMRTuneResults(res, as.df = TRUE)
 2: getBMROptResults(bmr, task.ids, learner.ids, as.df, "TuneWrapper", function
 3: getBMRObjects(bmr, task.ids, learner.ids, fun = f, as.df = as.df)
 4: lapply(task.ids, function(tid) {
    xs = lapply(learner.ids, function(lid) 
 5: FUN(X[[i]], ...)
 6: lapply(learner.ids, function(lid) {
    p = fun(bmr$results[[tid]][[lid]])
  
 7: FUN(X[[i]], ...)
 8: fun(bmr$results[[tid]][[lid]])
 9: cbind(iter = 1:niters, do.call(rbind.fill, xs))
10: cbind(deparse.level, ...)
11: data.frame(..., check.names = FALSE)
```

`getBMRTuneResults` with `as.df = FALSE` also shows the filtered features (not sure what the intended behavior should be).

```
getBMRTuneResults(res)
$`BostonHousing-example`
$`BostonHousing-example`$regr.rpart
NULL

$`BostonHousing-example`$regr.lm.filtered.tuned
$`BostonHousing-example`$regr.lm.filtered.tuned[[1]]
$`BostonHousing-example`$regr.lm.filtered.tuned[[1]]$TuneResult
Tune result:
Op. pars: fw.abs=12
mse.test.mean=18.9

$`BostonHousing-example`$regr.lm.filtered.tuned[[1]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  


$`BostonHousing-example`$regr.lm.filtered.tuned[[2]]
$`BostonHousing-example`$regr.lm.filtered.tuned[[2]]$TuneResult
Tune result:
Op. pars: fw.abs=13
mse.test.mean=23.6

$`BostonHousing-example`$regr.lm.filtered.tuned[[2]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  


$`BostonHousing-example`$regr.lm.filtered.tuned[[3]]
$`BostonHousing-example`$regr.lm.filtered.tuned[[3]]$TuneResult
Tune result:
Op. pars: fw.abs=12
mse.test.mean=31.1

$`BostonHousing-example`$regr.lm.filtered.tuned[[3]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat" 
```

I also tried to call `benchmark` with `extract = getTuneResult` for the above example. But that fails, too.

```
res = benchmark(tasks = bh.task, learners = lrns, resampling = outer, show.info = FALSE,
+   extract = getTuneResult)
Error in benchmark(tasks = bh.task, learners = lrns, resampling = outer,  : 
  Assertion on 'object' failed: Must have class 'TuneModel', but has class 'WrappedModel'

Enter a frame number, or 0 to exit   

 1: benchmark(tasks = bh.task, learners = lrns, resampling = outer, show.info =
 2: parallelMap(benchmarkParallel, split(as.matrix(inds), f = seq_row(inds)), m
 3: mapply(fun2, ..., MoreArgs = more.args, SIMPLIFY = FALSE, USE.NAMES = FALSE
 4: (function (index, learners, tasks, resamplings, measures, keep.pred = TRUE,
 5: resample(learners[[ind.learner]], tasks[[ind.task]], resamplings[[ind.task]
 6: parallelMap(doResampleIteration, seq_len(rin$desc$iters), level = "mlr.resa
 7: mapply(fun2, ..., MoreArgs = more.args, SIMPLIFY = FALSE, USE.NAMES = FALSE
 8: (function (learner, task, rin, i, measures, weights, model, extract, show.i
 9: extract(m)
10: assertClass(object, "TuneModel")
11: makeAssertion(res, vname(x, .var.name))
12: mstop("Assertion on '%s' failed: %s", var.name, msg)
```

**Comment by schiffner** [comment] 2015-09-16 00:08
The reason is that that the first learner `"regr.rpart"` is not tuned.
`extract = getTuneResult` works if only the tuned learner is used.

```
res = benchmark(tasks = bh.task, learners = lrn, resampling = outer, show.info = FALSE,
+   extract = getTuneResult)
```

Wouldn't we want that `getTuneResult` just returns `NULL` instead of throwing an error when the model does not inherit from  `TuneModel`?

**Comment by jakob-r** [comment] 2015-09-16 10:17
As I did the change in the default extract method i will have a closer look later. But we should discuss what is the expected behavior. 

1. Obvoiusly `getBMRTuneResult` should give the tuning result even if a FilterWrapper etc is used
2. Should `getTuneResult` really just return `NULL` if no `TuneResult` can be extracted? Sounds good, but maybe someone else also think about that.

**Comment by schiffner** [comment] 2015-09-16 11:31
Sorry, don't mean to be destructive, just want to list all the problems before we think about solutions.

Regarding benchmark experiments:  
I forgot to add yesterday that the default `extract` functions in `benchmark` return incorrect results. When you look at the result below, the optimal number of features `fw.abs` is 12 in iterations 1 and 3, but `$FilteredFeatures` always lists all 13 features.

```
res$result[[1]][["regr.lm.filtered.tuned"]]$extract
[[1]]
[[1]]$TuneResult
Tune result:
Op. pars: fw.abs=12
mse.test.mean=18.9

[[1]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  


[[2]]
[[2]]$TuneResult
Tune result:
Op. pars: fw.abs=13
mse.test.mean=23.6

[[2]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  


[[3]]
[[3]]$TuneResult
Tune result:
Op. pars: fw.abs=12
mse.test.mean=31.1

[[3]]$FilteredFeatures
 [1] "crim"    "zn"      "indus"   "chas"    "nox"     "rm"      "age"    
 [8] "dis"     "rad"     "tax"     "ptratio" "b"       "lstat"  
```

**Comment by schiffner** [comment] 2015-09-16 11:47
@zmjones : In order to not hold up any additions to the tutorial I did a quick fix for the nested resampling section that can be reverted as soon as this issue here is solved.

**Comment by jakob-r** [comment] 2015-09-16 12:13
No :smiley: Everything perfect and great that you spot everything! I think the problem here is that the function `getFilteredFeatures` is pretty "hardcoded" and works on every model. What it should do actually is only to work on a `FilterModel`. If `getFilteredFeatures` is called on another model class it should just go deeper until it eventually finds something or returns `NULL`.
That I will fix now as it is quite independent from the other issue.

**Comment by schiffner** [comment] 2015-09-16 12:30
Thanks very much @jakob-r. Agreed about `getFilteredFeatures`. It's the same with `getTuneResult`.

I played around a little more and have some more questions/problems we should discuss. I put them here because they are related, but can also open an extra-issue for this.

Here is a resampling example with feature filtering and tuning of the number of selected features:

```
set.seed(123)

## Tuning of the percentage of selected filters in the inner loop
lrn = makeFilterWrapper(learner = "regr.lm", fw.method = "chi.squared")
ps = makeParamSet(makeDiscreteParam("fw.abs", values = 1:13))
ctrl = makeTuneControlGrid()
inner = makeResampleDesc("CV", iters = 3)
lrn = makeTuneWrapper(lrn, resampling = inner, par.set = ps, control = ctrl, show.info = FALSE)

## Outer resampling loop
outer = makeResampleDesc("CV", iters = 3)
r = resample(learner = lrn, task = bh.task, resampling = outer, models = TRUE, show.info = FALSE,
extract = getFilteredFeatures)
r
```

`r$extract` here returns incorrect results (as already addressed above).

**Behavior of print methods**

When I look at the printed output of models I don't see `fw.abs`.

```
r$models

[[1]]
Model for learner.id=regr.lm.filtered.tuned; learner.class=TuneWrapper
Trained on: task.id = BostonHousing-example; obs = 337; features = 13
Hyperparameters: fw.method=chi.squared

[[2]]
Model for learner.id=regr.lm.filtered.tuned; learner.class=TuneWrapper
Trained on: task.id = BostonHousing-example; obs = 337; features = 13
Hyperparameters: fw.method=chi.squared

[[3]]
Model for learner.id=regr.lm.filtered.tuned; learner.class=TuneWrapper
Trained on: task.id = BostonHousing-example; obs = 338; features = 13
Hyperparameters: fw.method=chi.squared
```

When I unwrap it once by calling `getLearnerModel` I get the value of `fw.abs`.

```
m = r$models[[2]]
getLearnerModel(m)
Model for learner.id=regr.lm.filtered; learner.class=FilterWrapper
Trained on: task.id = BostonHousing-example; obs = 337; features = 13
Hyperparameters: fw.method=chi.squared,fw.abs=12
```

** getLearnerModel**

I'm not sure what `getLearnerModel` is supposed to return.
I always thought its main purpose is to extract the object returned by the underlying R learner,
in the example above the `lm` object. Not sure how deep this is supposed to go by default, as it already looks at 2 different levels, or if it would be better to let the user choose which level he wants.
To uncover the innermost object I currently must do this. :)

```
getLearnerModel(getLearnerModel(m), more.unwrap = TRUE)
Call:
stats::lm(formula = f, data = d)

Coefficients:
(Intercept)         crim           zn        indus          nox           rm  
   38.53895     -0.11988      0.06260      0.05951    -20.55294      3.60708  
        age          dis          rad          tax      ptratio            b  
    0.02024     -1.58118      0.32097     -0.01087     -1.02313      0.01196  
      lstat  
   -0.58720  
```

**Comment by berndbischl** [comment] 2015-09-18 09:55
This is a long thread now. I will look at it today.

**Comment by berndbischl** [comment] 2015-09-18 09:56
Most important question so far. Where is the formal documentation what is in the "extract" field, when I use a combination of wrappers?

**Comment by schiffner** [comment] 2015-09-18 10:16
Not exactly sure what you mean.

We don't really have a documentation of what is in `BenchmarkResult`.
The docs in `benchmark`and `resample` say that `getTuneResult`, `getFilteredFeatures`, `getFeatSelResult` are all applied by default.
So implicitly it's clear that you get more than one extraction result when more than one getter finds something. (But could be more explicit in the docs if we want this behavior.)

**Comment by berndbischl** [comment] 2015-09-18 10:23
That is exactly the problem here, that this is not written down. 

> We don't really have a documentation of what is in BenchmarkResult.

That was always stupid. Actually the structure is pretty simple, from what I see. 
It is basically a list of list of ResampleResults. 
And what is in the ResampleResults is documented pretty nicely, I would say.
But apparently what is in "extract" there, if now extract was done, was changed by @jakob-r.
The docs says it should be NULL. But code produces an empty list. 

This is what we need to discuss and change. The bug fixing here is then kind of of minor importance. As it should be simple.

**Comment by schiffner** [comment] 2015-09-18 10:43
Ok, hadn't noticed the empty list yet.
So todo:
* Enhance documentation of `ResampleResult`.
* Decide if we want NULL or an empty list if the default method couldn't extract anything in `resample` and doc it. (I would prefer NULL).

And we should check if all getters do meaningful things when applied to a Learner that is wrapped several times. Some of the stuff I noticed is already in the posts above.

**Comment by larskotthoff** [comment] 2015-10-24 05:37
What I got from the discussion is that, in addition to what Julia already mentioned, we also need to decide to what extent `getLearnerModel()` should do more "unpeeling" of wrapped models by default. It seems to me that an additional option to select which model in the stack of wrapped models to get would be useful (and maybe even a function that just shows the wrapping layers).

The same goes for the `print()` methods -- to what extent should these show information from wrapped models (and how many layers)?

This is not particularly urgent and needs some thought, so I'm pushing this back to 2.6. It's not a small change if we want everything to be consistent (and the tutorial needs to be updated/amended as well for this).

**Comment by jakob-r** [comment] 2015-10-26 10:31
It should be definitely a new thread/issue because here we are now discussing a lot of related but still different functions and functions on different classes.

**Comment by pat-s** [comment] 2018-10-28 20:51
> It should be definitely a new thread/issue because here we are now discussing a lot of related but still different functions and functions on different classes.

I am with Jakob here. Not sure what the current state of this issue is after reading it to the last comment. Closing here. If its still important to be tackled anytime soon we should open a clean issue.

**Closed by pat-s** 2018-10-28 20:51 UTC
