### ISSUE TITLE
Feature selection - parameter naming conflict

### ISSUE THREAD

**Issue by srp33** [mlr-org/mlr#1066] opened 2016-08-05 04:11 UTC
I really enjoy working with mlr, but I've run into a little problem, and I'm not sure how to get around it. I'm hoping you can help. I'm trying to do feature selection with the rf.min.depth function. I want to specify a value for the "method" parameter within the underlying library ( randomForestSRC::var.select). But there is also a "method" parameter in the generateFilterValuesData function for the learner name. Below is some example code along with the error I'm getting. I'm running R-3.3.1 and mlr version 2.9.

```
library(mlr)

parameterValues <- c(method="vh", conservative="low")
task <- makeClassifTask(data = iris, target = "Species")
fv <- generateFilterValuesData(task, method = "rf.min.depth", more.args=list("rf.min.depth"=parameterValues))
```

Error in randomForestSRC::var.select(getTaskFormula(task), getTaskData(task),  : 
  formal argument "method" matched by multiple actual arguments

Any suggestions?

**Comment by jakobbossek** [comment] 2016-08-08 10:23
The problem is that in an internal function `method` is set directly **and** via `...`. Definitely a bug. Going to fix this soon.

**Comment by berndbischl** [comment] 2016-08-10 02:02
@jakobbossek 
please close this when it is unit tested

**Comment by jakobbossek** [comment] 2016-08-11 11:27
Added test in b8c46bc. Closing.

**Closed by jakobbossek** 2016-08-11 11:27 UTC
Labels: bug

**Comment by srp33** [comment] 2016-08-11 13:44
Sorry for the dumb question, but what can I do if I want to apply this patch to my own analysis? I am currently using version 2.9.

**Comment by larskotthoff** [comment] 2016-08-11 13:51
You can install the development version of mlr with `devtools`:

    devtools::install_github("mlr-org/mlr")

**Comment by srp33** [comment] 2016-08-11 13:54
Will this be incorporated into version 2.10? If so, how soon do you expect that to be released? Thanks again!

**Comment by larskotthoff** [comment] 2016-08-11 13:55
Yes and we expect a release very soon.

**Comment by berndbischl** [comment] 2016-08-11 13:57
monday my holiday starts. i want to push to CRAN before this.

they should hopefully allow a 2nd release in 10 days.

**Comment by srp33** [comment] 2016-08-11 13:58
What would be included in the 2nd release?

**Comment by larskotthoff** [comment] 2016-08-11 14:00
We are still working on this.

**Comment by berndbischl** [comment] 2016-08-11 14:05
> What would be included in the 2nd release?

simply read the NEWS in the GH repo. you can see what we are changing there.

**Comment by srp33** [comment] 2016-08-29 18:49
Sorry to keep this thread going, but do you know how soon version 2.10 will be live on CRAN? It is still showing as 2.9. Thanks!
