### ISSUE TITLE
`createDummyFeatures` should sanitize names

### ISSUE THREAD

**Issue by d125q** [mlr-org/mlr#892] opened 2016-05-14 10:55 UTC
Assume I have a data frame `df` which contains a factor column `quan` with levels `<5` and `>5` (which are illegal R variable names).

Running `createDummyFeatures(df)` gives back a data frame with columns `quan.<5` and `quan.>5`.  This data frame afterwards fail strict name checks and is unusable in tasks, learners, etc.  Thus, I propose that `createDummyFeatures` should sanitize names by removing illegal characters and uniquifying the resulting names.

**Comment by catastrophic-failure** [comment] 2016-05-14 17:38
`make.names` should do the trick, but it would make both read the same, appending a `.1` to the second one. I'm fairly sure calling `data.frame` does that automatically.

```splus
make.names(c("<5",">5"), unique = TRUE)
```

**Comment by ja-thomas** [comment] 2017-03-07 14:31
@Coorsaa since you updated the `createDummyFeature` functionality. Can you check if that problem is still here and if so fix it.

**Comment by daryabusen** [comment] 2017-11-24 14:46
I´m working on this

**Comment by daryabusen** [comment] 2017-11-27 17:54
We could not reproduce the error
 
```
 
quan = factor(c("<5", ">5"))
 
test.df = data.frame(quan)
 
names(createDummyFeatures(test.df))
 
```
 
returns:
 
`# [1] "quan..5"   "quan..5.1"`
 
So it seems like the error is already fixed.

**Comment by christophM** [comment] 2017-11-28 10:16
@daryabusen could you please write a unit test for the names to make sure the issue also stays fixed in the future.

**Comment by daryabusen** [comment] 2017-12-08 13:07
Created Pull Request #2096

**Closed** 2019-03-20 22:40 UTC
Labels: effort-simplefix, innolab1718, prio-low, type-bug
