### ISSUE TITLE
is facet="nested_cv_run" working in plotHyperParsEffect?

### ISSUE THREAD

**Issue by danielhomola** [mlr-org/mlr#1388] opened 2016-12-14 12:08 UTC
I'm trying to tune a classif.learner with nested CV, and then get one 2D heatmap for each of my outer folds from ```plotHyperParsEffect```. As far as I understand I have to use ```facet="nested_cv_run"``` to achieve this. However I keep getting a single plot. Am I missing something here?

Many thanks!

d

```
library(mlr)
library(readr)
library(parallelMap)
library(ggplot2)

# load Breast Cancer dataset, impute missing
data(BreastCancer, package="mlbench")
df <- BreastCancer
target <- "Class"
df$Id <- NULL

# impute missing values abd define classification task
impute_col_median <- function(x){
  # Retruns a single column where NA is replaced with median
  x <- as.numeric(as.character(x))
  x[is.na(x)] <- median(x, na.rm=TRUE)
  x 
}

data_without_target <- function(df, target){
  # Return df without the target column
  df[,-which(colnames(df)==target)]
}

impute_data <- function(df, target){
  # Impute missing values in cols with median except in target
  df_imp <- data_without_target(df, target)
  df_imp <- as.data.frame(sapply(df_imp, impute_median))
  df[,-which(colnames(df)==target)] <- df_imp
  df
}

df <- impute_data(df, target)
classif.task <- makeClassifTask(id="BreastCancer", data=df, target=target)

# make random linkage

# fit elastic net with nested matched CV on a random grid
ps <- makeParamSet(
  makeNumericParam("alpha", lower=0, upper=1),
  makeNumericParam("lambda", lower=-3, upper=3, trafo=function(x) 10^x)
)

ctrl <- makeTuneControlRandom(maxit=200L)
inner <- makeResampleDesc("CV", iters=3)

m1 <- auc
m2 <- setAggregation(auc, test.sd)
m_all <- list(m1, m2)

lrn <- makeLearner("classif.glmnet", predict.type="prob")
lrn_wrap <- makeTuneWrapper(lrn, resampling=inner, par.set=ps, control=ctrl,
                            show.info=FALSE, measures=m_all)

outer <- makeResampleDesc("CV", iters=3)

parallelStartSocket(8, level="mlr.tuneParams")

r <- resample(lrn_wrap, classif.task, resampling=outer, models=TRUE,
              extract=getTuneResult, show.info=FALSE)
parallelStop()

# plot the two params with a random search
resdata = generateHyperParsEffectData(r, trafo = F, include.diagnostics = FALSE)
plt = plotHyperParsEffect(resdata, x = "alpha", y = "lambda", z = "auc.test.mean",
                          plot.type = "heatmap", interpolate = "regr.earth",
                          facet="nested_cv_run", show.experiments = T, nested.agg = mean)
min_plt = min(resdata$data$auc.test.mean, na.rm = TRUE)
max_plt = max(resdata$data$auc.test.mean, na.rm = TRUE)
med_plt = mean(c(min_plt, max_plt))
plt + scale_fill_gradient2(breaks = seq(min_plt, max_plt, length.out = 5),
                           low = "blue", mid = "white", high = "red", midpoint = med_plt)
```

**Comment by danielhomola** [comment] 2016-12-14 14:00
Shouldn't https://github.com/mlr-org/mlr/blob/master/R/generateHyperParsEffect.R#L428 be 
```plt = plt + facet_wrap(~facet)```?

**Comment by danielhomola** [comment] 2016-12-14 16:35
Also it seems like that the ```partial.dep``` param described here:
https://mlr-org.github.io/mlr-tutorial/devel/html/hyperpar_tuning_effects/index.html#visualizing-the-effects-of-more-than-2-hyperparameters

is not implemented yet (or any more?)
https://www.rdocumentation.org/packages/mlr/versions/2.9/topics/generateHyperParsEffectData?

Thanks a lot for the help in advance!

**Comment by MasonGallo** [comment] 2016-12-15 16:47
This is quite a large code sample. My assumption is that you want n facetted heatmaps with alpha vs lambda on each. As specified in the docs, 2d nested cv is aggregated based on the `nested.agg` argument. 

Adding true facet support for >=1d is on my TODO list but I won't have time to get to it until after the new year. If you would liek to submit a PR, I'm sure the team would be happy to review. :)

**Comment by danielhomola** [comment] 2016-12-15 17:29
Thanks a lot for getting back to me on this and also writing these really nice convenience functions. I checked the source code and realised this isn't implemented yet. As I'm not really familiar with the source, this might take a lot longer for me than for you, so I'll just wait for you if that's OK.. If I find myself being super bored over the holidays, I might surprise you with a PR :)

**Comment by danielhomola** [comment] 2016-12-24 03:12
Hi Mason!

I've run into this bug and it's driving me crazy..

I'm trying to write a wrapper around your ```plotHyperParsEffect```, so it plots every hyper parameter combination. It works really well with 2 parameters, but when I try it with a model that has three models it fails.

```generateHyperParsEffectData``` runs without any hickups and generates the regular object with ```$data``` being a data frame with 3 hyper parameter columns. When I try to plot the first two of these 3 like so:
```plt <- plotHyperParsEffect(df, x=axes[1], y =axes[2], z="auc.test.mean",
                           plot.type="heatmap", interpolate="regr.earth", 
                           show.experiments=T, nested.agg=mean)```

I get is this:
```Error in `[.data.frame`(d, , c(hyperpars.effect.data$hyperparams, "learner_status")) : 
  undefined columns selected```

My hunch is that the problem is somewhere here:
https://github.com/mlr-org/mlr/blob/master/R/generateHyperParsEffect.R#L398
but I couldn't debug it, even though I spend 1.5 hours on it.. 

Any help would be really appreciated!

**Comment by danielhomola** [comment] 2016-12-24 16:18
Sorry, ignore my previous one, it took me 2.5 hours but solved it.. If you have more than 2 hyperparams in the `resdata` from `generateHyperParsEffectData`, you'll need to discard the hyperparameter(s) from `resdata$hyperparam` that you are not planning to plot.. Btw this wrapper I wrote will generate a plot for every pair of hyper parameter combo and also facet the plots by iteration. It will save the plot as pdfs to an output folder. Here it is if anyone interested:

`
plot_hyperpar_pairs <- function(results, perf_metric, output_folder="", trafo=F){
  # Plots the performance metric surface for all hyper parameter combinations 
  # across all outer folds
  library(gridExtra)
  
  # Setup the plot
  outer_fold_n <- length(results$models)
  subplot_n <- outer_fold_n + 1
  
  # Generate data for plots
  resdata <- generateHyperParsEffectData(results, trafo=trafo)
  
  # Generate hyper param pairs to plot
  all_axes <- t(combn(resdata$hyperparams, 2))
  
  # Check output folder, create it if needed
  if (output_folder == ""){
    output_folder = getwd()
  }else{
    output_folder =file.path(getwd(), output_folder)
    if (!file.exists(output_folder)){
      dir.create(output_folder)
    }
  }
  
  # Set default font size
  theme_set(theme_minimal(base_size = 10))
  
  # Go through all variable pairs  
  for (p in 1:nrow(all_axes)){
    # Go through each outer fold + a combined plot
    subplots <- list()
    # Get axes of the plot
    axes <- all_axes[p, ]
    for (i in 1:subplot_n){
      # df stores the relevant data of each outer fold
      df <- resdata
      # Discard hyperparams that we are not plotting, otherwise we get a nasty
      # bug that took me 3 hours to debug
      df$hyperparams <- axes[1:2]
      if (i==1){
        title = paste("All outer folds combined")
      }else{
        title = paste("Outer fold", as.character(i-1))
        # Faceting with nested_cv_run is not implemented yet, we do it manually
        df$data <- df$data[df$data$nested_cv_run==i-1,]
        
      }
      min_plt <- min(df$data[perf_metric], na.rm=T)
      max_plt <- max(df$data[perf_metric], na.rm=T)
      med_plt <- mean(c(min_plt, max_plt))
      
      plt <- plotHyperParsEffect(df, x=axes[1], y =axes[2], z=perf_metric,
                          plot.type="heatmap", interpolate="regr.earth", 
                          show.experiments=T) +
             scale_fill_gradient2(breaks=seq(min_plt, max_plt, length.out=5),
             low="grey", high="blue", midpoint=med_plt) +
             ggtitle(title) +
             theme(panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   axis.line = element_line(colour = "grey"))
      
      # Add the sublots to build multiplot
      subplots[[length(subplots)+1]] <- plt
    }
    
    # Save each multiplot of hyper param pair into the output folder
    main_title <- paste(axes[1],"vs", axes[2])
    file_name <- paste(paste(axes[1], axes[2], sep='_'), ".pdf", sep='')
    output_path <- file.path(output_folder, file_name)
    multiplot <- marrangeGrob(subplots, nrow=2, ncol=2, top=main_title)
    ggsave(output_path, multiplot)
  }
}`

**Comment by MasonGallo** [comment] 2016-12-24 20:08
@danielhomola if you believe there is a bug, please post a reproducible example.

I'm not sure what it is you're aiming to do here. If you're trying to visualize with 2+ hyperparameters, you will prob need to use partial dependence.

**Comment by danielhomola** [comment] 2017-01-04 13:31
@MasonGallo you're right, this is what your partial dep plots are for, but that functionality is still in the development branch (if I'm not mistaken). I want to use the stable release that's why I came up with this hacky alternative visualisation.

**Comment by danielhomola** [comment] 2017-01-26 13:56
@MasonGallo I got the development version of mlr, so I'm not using the `plotHyperParsEffect` with `partial.dep=T` it works great. 

- When I'm plotting a single variable, do you automatically take the mean of the curves within the partial dependence plots? Could I change the aggregation method to median, or even better plot them all? 
- Also, when we're plotting two variables as a heatmap, I guess the following is used under the hood:
`pd.lst = generatePartialDependenceData(fit.classif, iris.task, c("Petal.Width", "Petal.Length"), FALSE)`
But how is the averaging done across the samples? Couldn't we visualise the resulting heatmap with the experiments and interpolation as in the case of two hyperparameters?

Thanks a bunch for the help in advance!!

**Comment by MasonGallo** [comment] 2017-01-26 17:35
> When I'm plotting a single variable, do you automatically take the mean of the curves within the partial dependence plots? Could I change the aggregation method to median, or even better plot them all?

You can use the `nested.agg` argument to change the function (by default it's `mean`)

> But how is the averaging done across the samples? Couldn't we visualise the resulting heatmap with the experiments and interpolation as in the case of two hyperparameters?

I'm not sure what you mean here. Can you try explaining another way (maybe with more code)?

**Comment by danielhomola** [comment] 2017-01-27 11:36
Thanks a lot for getting back to me and for coding up these nice plotting functions!

When I do 
`plt <- plotHyperParsEffect(df, x=hyper1, y=hyper2, z=perf_metric,
                                   plot.type="heatmap", show.experiments=T,
                                   partial.dep.learn="regr.earth")`
The experiments will not show as individual dots on the heatmap, although this would be useful. Also I fail to see why can't we use the continuous interpolation heatmap with partial dependence and why the much simpler tiled heatmap plot.type is enforced. ..

**Comment by MasonGallo** [comment] 2017-01-27 18:24
Glad to hear you're getting use out of them! Interpolation isn't necessary in that case since partial dependence already produces a grid. Per the documentation, `show.experiments` arg is not used with partial dependence due to the nature of partial dependence.

I'm going to close this issue since I don't want to clog up our issues pipeline. I am planning on integrating facet soon (tm). Feel free to open a new issue if you have anything else.

**Closed by MasonGallo** 2017-01-27 18:24 UTC
Labels: enhancement, prio-low
